### ISSUE TITLE
[BUG] Account ID Found & Not Found After Deleting Public Keys

### ISSUE THREAD

**Issue by joesixpack** [nearprotocol/stakewars#101]
The below happened after I (tried to?) removed all public keys associated with the account ID:

![image](https://user-images.githubusercontent.com/23145642/71251770-16dbb800-22d8-11ea-8c59-c02e88f0fa4e.png)

**Comment by frol** [comment]
Related to https://github.com/nearprotocol/near-wallet/issues/289

**Comment by potatodepaulo** [comment]
Points assigned. Issue tracked in issue linked above.
