### ISSUE TITLE
BUG [Downloading headers 99% too long, and node not working]

### ISSUE THREAD

**Issue by etherscam** [nearprotocol/stakewars#104]
### I completely restart the node

1) Deleted the folder ~ / near
2) Updated npm near-shell (and used install - update does not work)
3) Made stake = 100.01 (I have 102,662.43944 на on the wallet balance)
4) Run node using ./scripts/start_stakewars.py
5) Loading headers 99

`[2019-12-23T08: 53: 58Z INFO near_network :: peer_manager] Server listening at ed25519: 75E44m1qEcqWULxUYZbCXpjQEtDgU7q94SW4k9o5D5Ft@0.0.0.0: 24567 [2019-12-23T08: 54: 18Z INFO near_client] - / 7 3/3/40 peers ⬇ 0 B / s ⬆ 0 B / s 0.00 bps 0 gas / s CPU: 182%, Mem: 139.5 MiB [2019-12-23T08: 54: 40Z INFO near_client :: info] # 0 Downloading headers 99% - / 7 7/2/40 peers ⬇ 14.0kiB / s ⬆ 44 B / s 0.00 bps 0 gas / s CPU: 186%, Mem: 148.3 MiB`

6) I can not become a validator
***I also noticed that someone in accounts.csv is a test node (error in the photo)***

**Expected behavior OR Outcome of test**

**Specs (please complete the following information):**
 - OS: Ubuntu 18...
- Which cloud / on-premise: 
- CPU: 2
- RAM: 4
- Disk space: 200

```
nvm version
v13.3.0
npm --version
6.13.1
node --version
v13.3.0

```

**Screenshots Optional**
![image](https://user-images.githubusercontent.com/40215726/71349082-26305f00-257f-11ea-8052-5f7c458943f4.png)
![image](https://user-images.githubusercontent.com/40215726/71349259-a2c33d80-257f-11ea-879b-a7c19c036d7a.png)

**Comment by potatodepaulo** [comment]
Thanks! Assigned points.
