### ISSUE TITLE
BUG Near shell installation fail on Linux

### ISSUE THREAD

**Issue by xiaohanzhu** [nearprotocol/stakewars#105]
**Describe the bug or test**
Trying to install near-shell on Ubuntu 18 with
sudo npm install -g near-shell

Received the following messages at the end:

/usr/local/bin/near -> /usr/local/lib/node_modules/near-shell/bin/near
/usr/local/bin/near-cli.js -> /usr/local/lib/node_modules/near-shell/bin/near-cli.js
/usr/local/lib
└── near-shell@0.17.3

npm WARN optional Skipping failed optional dependency /near-shell/jest-haste-map/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.11

**Specs (please complete the following information):**
 - OS: Ubuntu
- Which cloud / on-premise: AWS
- CPU: 
- RAM: 
- Disk space: 

**Additional context**

**Screenshots Optional**

**Comment by frol** [comment]
The log seems usual to me. What makes you believe that it failed to install?

**Comment by frol** [comment]
Closing due to the inactivity.
