### ISSUE TITLE
BUG [Decoder error]

### ISSUE THREAD

**Issue by etherscam** [nearprotocol/stakewars#106]
**Describe the bug or test**
Completely restarted the node
* Was a network validator for about an hour
There was an error and apparently the network stopped working

**How to Reproduce**
Stake 200 NEAR
RUN NODE WITH DOCKER

```
thread 'main' panicked at 'Decoder error: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Non-zero exit code: 1" }', src/libcore/result.rs:1165:5
```

OS: Ubuntu 18...
Which cloud / on-premise:
CPU: 2
RAM: 4
Disk space: 200
nvm version
v13.3.0
npm --version
6.13.1
node --version
v13.3.0

**Additional context**

**Screenshots Optional**
![image](https://user-images.githubusercontent.com/40215726/72062004-feaff500-32e7-11ea-9961-e3be48cf0987.png)

**Comment by frol** [comment]
The error indicates that the network is down. [Stake Wars has been paused](https://nearprotocol.com/blog/were-pausing-stake-wars/).
