### ISSUE TITLE
BUG [NEAR STATE] 

### ISSUE THREAD

**Issue by etherscam** [nearprotocol/stakewars#107]
Server error occurred after calling near stake<><>

**How to Reproduce**
```
[WARNING] Didn't find config at /home/ubuntu1/nearcore/src/config, using default shell config
{
  networkId: 'tatooine',
  nodeUrl: 'https://rpc.tatooine.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.tatooine.nearprotocol.com'
}
Error:  BadGatewayError: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

```

OS: Ubuntu 18...
Which cloud / on-premise:
CPU: 2
RAM: 4
Disk space: 200
nvm version
v13.3.0
npm --version
6.13.1
node --version
v13.3.0.
![image](https://user-images.githubusercontent.com/40215726/72064028-0ec9d380-32ec-11ea-96dd-d33b27882e44.png)

**Comment by frol** [comment]
The error indicates that the network is down. [Stake Wars has been paused](https://nearprotocol.com/blog/were-pausing-stake-wars/).
