### ISSUE TITLE
[SCENARIOS] 

### ISSUE THREAD

**Issue by eorituz** [nearprotocol/stakewars#108]
**Scenarios Run**
Run node
Ran 10 nodes (for ~2 weeks)
Staked some of those nodes with different amounts

**Nodes**
I called all my Nodes `arno_nym*`

**Outcome**
1) Obviously the nodes got stuck quite frequent due to network issues but updating the stakewars code and running it with docker was a great UX. Super easy to use and easy to update.

2) The automated transition from Tatooine to testnet worked flawlessly. According to https://explorer.nearprotocol.com/nodes my node now runs on testnet.

3) I experienced quite some issues with the [wallet](https://wallet.tatooine.nearprotocol.com/) (account creation not possible, wallet offline ...) as well as issues with the network and stuck/not syncing nodes. But once both components where live staking via worked fine.

**Specs (please complete the following information):**
 - OS: Ubuntu 18.04
- Which cloud / on-premise: DigitalOcean Server (location FRAnkfurt)
- CPU: 2 CPUs
- RAM: 4 GB
- Disk space:  80 GB

**Comment by potatodepaulo** [comment]
Thanks! Adding points for this.
