### ISSUE TITLE
[TEST][benchmark] Docker setup only takes advantage of 1 cpu

### ISSUE THREAD

**Issue by andreisid** [nearprotocol/stakewars#14]
100% usage on cpu core 1 and 0% on cpu core 2 
**To Reproduce**
1. installed validator
2. let it run as part of stake wars

**Expected behavior OR Outcome of test**
![image](https://user-images.githubusercontent.com/12342269/68147920-bbca4d80-ff43-11e9-915a-0ae840314ee9.png)

**Specs (please complete the following information):**
 - OS:ubuntu 18.04
- Which cloud / on-premise: aws
- CPU: 2
- RAM: 4
- Disk space: 50

**Comment by ailisp** [comment]
@SkidanovAlex mentioned our code is single thread, did i misunderstand and is it something we can change soon?

**Comment by bowenwang1996** [comment]
It's not entirely single threaded, but it uses at most 2 cores I think

**Comment by potatodepaulo** [comment]
This is not an issue, this is simply how the system works. For this to receive points, you can submit this with a compelling recommendation for how you would like to use multiple cores.
