### ISSUE TITLE
[BUG] Unprecise description of Delegation Contract initialisation

### ISSUE THREAD

**Issue by eorituz** [nearprotocol/stakewars#160]
**Describe the bug or test**
I tried to deploy a delegation contract for staking as mentioned in the [readme](https://github.com/near/initial-contracts/tree/master/staking-pool).

However, I couldn't figure out what the `stake_public_key` is / where to get it from.
The `stake_public_key` It is needed to initialize the newly deployed delegation contract. 
 ```
near call my_validator new '{"owner": "my_validator", "stake_public_key": "CE3QAXyVLeScmY9YeEyR3Tw9yXfjBPzFLzroTranYtVb"}' --account_id my_validator`)
```
Also, it would be great to add the additional required arguments `owner_id` and `max_number_of_slots` in the json.

**How to Reproduce**
1. Go to https://github.com/near/initial-contracts/tree/master/staking-pool
2. Set everything up as described in the readme
3. Try to call `new` of the newly deployed "my_validator" contract 
```
near call my_validator new '{"owner": "my_validator", "stake_public_key": "CE3QAXyVLeScmY9YeEyR3Tw9yXfjBPzFLzroTranYtVb"}' --account_id my_validator
```

**Expected behavior OR Outcome of test**
I'd like some explanation about what the `stake_public_key` is.
Additionally adding the missing arguments `owner_id` and `max_number_of_slots` in the exemplary command would be great

**Comment by eorituz** [comment]
One more thing that came to my mind:

**Comment by jimmy3dita** [comment]
Hi, we updated the contract, it should be more clear now: https://github.com/near/initial-contracts/tree/master/staking-pool
