### ISSUE TITLE
[BUG] Cant recover account with email nor phone on betanet wallet

### ISSUE THREAD

**Issue by novy4** [nearprotocol/stakewars#174]
**Describe the bug or test**
I wanted to restart my validator node after this night reset of the betanet. Updated npm package and I wanted to login. This time it gives near.org domain to login. I've navigated the link and it asking to create an account. I clicked the recovery and there is only seed phrase option. No email or phone options are active. 
I found an old recovery email in my inbox. Changed the domain from nearprotocol.com to near.org. A page shows next text:

"Restore Account
Click "Continue" to restore your account: @novy.betanet
If this isn't your preferred browser, copy the URL and complete this process in your browser of choice."

Then I clicked on "continue button" and received a message:

"Link Expired
Please check your email or phone for the most recent message. Links in all earlier messages are invalid."

I can't recover my account with email.

**How to Reproduce**
1. Go to email
2. Click on recovery link
3. On the page click continue
4. See Expired message

**Expected behavior OR Outcome of test**
I should successfully access my account after recovery process 

**Screenshots Optional**
https://prnt.sc/sfws8i
https://prnt.sc/sfwrne

**Comment by c29r3** [comment]
Same problem

**Comment by bowenwang1996** [comment]
@vgrichina @kcole16

**Comment by MBGBuzzer** [comment]
Same problem

**Comment by novy4** [comment]
any activity on this?

**Comment by kcole16** [comment]
Hi @novy4, would you mind joining our [slack](https://near-community.slack.com/join/shared_invite/zt-dqpw6l4l-gMKRRgBsgf92_UkzmyXGWg#/), or messaging me on Telegram (@kendallc)?

Having a hard time reproducing this (though seems like several similar instances).
