### ISSUE TITLE
[TEST][benchmark] Use Docker memory limits

### ISSUE THREAD

**Issue by mbucci** [nearprotocol/stakewars#18]
**Describe the bug or test**
Use Docker memory limits to control memory leak #17 

**To Reproduce**
1. Run a node with Docker memory limits (e.g. `docker run ... --memory=4g ...`)

**Expected behavior OR Outcome of test**
Docker memory usage is capped at a reasonable value (e.g. 1g, 2g, or 4g)

**Specs (please complete the following information):**
 - OS: Amazon Linux 2
- Which cloud / on-premise: Cloud (AWS EC2)
- CPU: 8
- RAM: 32
- Disk space: 500GB

**Additional context**
[limit docker resources.](https://docs.docker.com/config/containers/resource_constraints/)

**Comment by sweetpotatoz** [comment]
git pull

edited nodelib.py under run_docker function to include -m 2g
(copy the nodelib.py to other filename as backup)

```
line135                    '-d', '-p', rpc_port, '-p', network_port, '-v', '%s:/srv/near' % home_dir,
line136                    '-m', '2g',
line137                    '-v', '/tmp:/tmp',
```
node now can run without being stopped.

**Comment by ailisp** [comment]
Yeah this is related to memory leak issue. If that's resolved this cap isn't needed, and thanks @mbucci and @sweetpotatoz for providing a reasonable config solution for now. @bowenwang1996 do you want me to add this to our nodelib?

**Comment by bowenwang1996** [comment]
We haven't established SLA on memory usage yet so we don't actually know what the peak usage would be like once we fix the memory leak issues. So I suggest we postpone this for now.

**Comment by ailisp** [comment]
sounds good
