### ISSUE TITLE
[BEND][bug] State Sync issues

### ISSUE THREAD

**Issue by mbucci** [nearprotocol/stakewars#19]
**Describe the bug or test**
`State Sync` often times out. Additionally, several 

```
Received Sync while Connecting from Outbound connection.
``` 
messages spam stdout shortly after node startup and then intermittently.

**To Reproduce**
1. Run a node

**Expected behavior OR Outcome of test**
`State sync` runs more reliably 

**Specs (please complete the following information):**
 - OS: Amazon Linux 2
- Which cloud / on-premise: Cloud (AWS EC2)
- CPU: 8
- RAM: 32
- Disk space: 500GB 

**Additional context**

**Screenshots Optional**
<img width="389" alt="Screen Shot 2019-11-04 at 4 50 56 PM" src="https://user-images.githubusercontent.com/4140086/68161182-4c446600-ff23-11e9-9bf3-f4d60ba15375.png">
<img width="546" alt="Screen Shot 2019-11-04 at 4 36 59 PM" src="https://user-images.githubusercontent.com/4140086/68161183-4cdcfc80-ff23-11e9-8192-af4a84db7246.png">

**Comment by bowenwang1996** [comment]
This is not a bug but rather an innocuous behavior that can happen in normal situation as well.
