### ISSUE TITLE
abnormal exit while waiting peer

### ISSUE THREAD

**Issue by hoekevin** [nearprotocol/stakewars#2]
[2019-10-22T10:54:16Z INFO  near_client::info] #   28780 Waiting for peers -/1  2/1/40 peers ⬇ 1.9MiB/s ⬆ 20.4kiB/s 0.00 bps 0 gas/s CPU: 36%, Mem: 134.0 MiB
[2019-10-22T10:54:26Z INFO  near_client::info] #   28780 Waiting for peers -/1  2/1/40 peers ⬇ 1.9MiB/s ⬆ 20.5kiB/s 0.00 bps 0 gas/s CPU: 43%, Mem: 134.0 MiB
[2019-10-22T10:54:36Z INFO  near_client::info] #   28780 Waiting for peers -/1  2/1/40 peers ⬇ 1.9MiB/s ⬆ 20.8kiB/s 0.00 bps 0 gas/s CPU: 29%, Mem: 134.0 MiB
[2019-10-22T10:54:46Z INFO  near_client::info] #   28780 Waiting for peers -/1  2/1/40 peers ⬇ 1.8MiB/s ⬆ 19.4kiB/s 0.00 bps 0 gas/s CPU: 40%, Mem: 134.0 MiB
[2019-10-22T10:54:56Z INFO  near_client::info] #   28780 Waiting for peers -/1  2/1/40 peers ⬇ 1.8MiB/s ⬆ 19.5kiB/s 0.00 bps 0 gas/s CPU: 39%, Mem: 134.0 MiB
[2019-10-22T10:55:06Z INFO  near_client::info] #   28780 Waiting for peers -/1  2/1/40 peers ⬇ 1.8MiB/s ⬆ 19.2kiB/s 0.00 bps 0 gas/s CPU: 45%, Mem: 134.0 MiB
[2019-10-22T10:55:16Z INFO  near_client::info] #   28780 Waiting for peers -/1  2/1/40 peers ⬇ 1.9MiB/s ⬆ 20.5kiB/s 0.00 bps 0 gas/s CPU: 53%, Mem: 134.0 MiB
[2019-10-22T10:55:26Z INFO  near_client::info] #   28780 Waiting for peers -/1  2/1/40 peers ⬇ 2.0MiB/s ⬆ 22.2kiB/s 0.00 bps 0 gas/s CPU: 46%, Mem: 134.0 MiB
/usr/local/bin/run.sh: line 24:    25 Illegal instruction     (core dumped) near --home=${NEAR_HOME} run --boot-nodes=${BOOT_NODES}
*** /usr/local/bin/run.sh exited with status 132.
*** Shutting down runit daemon (PID 20)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
Oct 22 10:55:29 0c7397ffd925 syslog-ng[13]: syslog-ng shutting down; version='3.13.2'
*** Killing all processes...

**Comment by hoekevin** [comment]
root@9d3e57b4db7b:/var/log# cat messages
Oct 22 15:36:41 9d3e57b4db7b syslog-ng[13]: syslog-ng starting up; version='3.13.2'
Oct 22 15:36:58 9d3e57b4db7b syslog-ng[13]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:37:01 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:37:22 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:37:25 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:38:06 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:38:08 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:38:37 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:38:39 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:38:56 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:38:58 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:39:24 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:39:26 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:39:47 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:39:49 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:40:48 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:40:50 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:41:17 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:41:19 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:41:32 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:41:34 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:41:52 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:41:54 9d3e57b4db7b syslog-ng[13]: syslog-ng starting up; version='3.13.2'
Oct 22 15:42:28 9d3e57b4db7b syslog-ng[13]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:42:31 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:44:30 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:44:33 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:44:50 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:44:52 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:45:38 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:45:40 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:46:07 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:46:09 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:46:29 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:46:32 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:46:42 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:46:44 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:47:06 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:47:09 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:47:44 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:47:46 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'

**Comment by hoekevin** [comment]
root@9d3e57b4db7b:/var/log# cat syslog
Oct 22 15:36:41 9d3e57b4db7b syslog-ng[13]: syslog-ng starting up; version='3.13.2'
Oct 22 15:36:41 9d3e57b4db7b cron[24]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:36:41 9d3e57b4db7b cron[24]: (CRON) INFO (Running @reboot jobs)
Oct 22 15:36:58 9d3e57b4db7b syslog-ng[13]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:37:01 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:37:01 9d3e57b4db7b cron[22]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:37:01 9d3e57b4db7b cron[22]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:37:22 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:37:25 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:37:26 9d3e57b4db7b cron[25]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:37:26 9d3e57b4db7b cron[25]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:38:06 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:38:08 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:38:08 9d3e57b4db7b cron[22]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:38:08 9d3e57b4db7b cron[22]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:38:37 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:38:39 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:38:40 9d3e57b4db7b cron[25]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:38:40 9d3e57b4db7b cron[25]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:38:56 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:38:58 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:38:59 9d3e57b4db7b cron[25]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:38:59 9d3e57b4db7b cron[25]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:39:24 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:39:26 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:39:26 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:39:26 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:39:47 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:39:49 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:39:49 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:39:49 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:40:48 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:40:50 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:40:50 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:40:50 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:41:17 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:41:19 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:41:19 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:41:19 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:41:32 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:41:34 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:41:34 9d3e57b4db7b cron[22]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:41:34 9d3e57b4db7b cron[22]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:41:52 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:41:54 9d3e57b4db7b syslog-ng[13]: syslog-ng starting up; version='3.13.2'
Oct 22 15:41:55 9d3e57b4db7b cron[27]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:41:55 9d3e57b4db7b cron[27]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:42:28 9d3e57b4db7b syslog-ng[13]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:42:31 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:42:32 9d3e57b4db7b cron[25]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:42:32 9d3e57b4db7b cron[25]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:44:30 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:44:33 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:44:33 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:44:33 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:44:50 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:44:52 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:44:53 9d3e57b4db7b cron[25]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:44:53 9d3e57b4db7b cron[25]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:45:38 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:45:40 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:45:40 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:45:40 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:46:07 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:46:09 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:46:09 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:46:09 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:46:29 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:46:32 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:46:32 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:46:32 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:46:42 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:46:44 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:46:44 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:46:44 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:47:06 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:47:09 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:47:09 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:47:09 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:47:44 9d3e57b4db7b syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
Oct 22 15:47:46 9d3e57b4db7b syslog-ng[12]: syslog-ng starting up; version='3.13.2'
Oct 22 15:47:46 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:47:46 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 16:17:01 9d3e57b4db7b CRON[95]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

**Comment by hoekevin** [comment]
root@9d3e57b4db7b:/var/log# cat cron.log
Oct 22 15:36:41 9d3e57b4db7b cron[24]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:36:41 9d3e57b4db7b cron[24]: (CRON) INFO (Running @reboot jobs)
Oct 22 15:37:01 9d3e57b4db7b cron[22]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:37:01 9d3e57b4db7b cron[22]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:37:26 9d3e57b4db7b cron[25]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:37:26 9d3e57b4db7b cron[25]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:38:08 9d3e57b4db7b cron[22]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:38:08 9d3e57b4db7b cron[22]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:38:40 9d3e57b4db7b cron[25]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:38:40 9d3e57b4db7b cron[25]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:38:59 9d3e57b4db7b cron[25]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:38:59 9d3e57b4db7b cron[25]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:39:26 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:39:26 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:39:49 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:39:49 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:40:50 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:40:50 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:41:19 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:41:19 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:41:34 9d3e57b4db7b cron[22]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:41:34 9d3e57b4db7b cron[22]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:41:55 9d3e57b4db7b cron[27]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:41:55 9d3e57b4db7b cron[27]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:42:32 9d3e57b4db7b cron[25]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:42:32 9d3e57b4db7b cron[25]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:44:33 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:44:33 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:44:53 9d3e57b4db7b cron[25]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:44:53 9d3e57b4db7b cron[25]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:45:40 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:45:40 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:46:09 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:46:09 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:46:32 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:46:32 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:46:44 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:46:44 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:47:09 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:47:09 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 15:47:46 9d3e57b4db7b cron[23]: (CRON) INFO (pidfile fd = 3)
Oct 22 15:47:46 9d3e57b4db7b cron[23]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Oct 22 16:17:01 9d3e57b4db7b CRON[95]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

**Comment by hoekevin** [comment]
I read the code and find that only "ulimit -c unlimited" has been set,   kernel.core_pattern in /etc/sysctl.conf has not been set, so I can not find any coredump file in the container system of nearcore.

**Comment by bowenwang1996** [comment]
Yes this issue is fixed in https://github.com/nearprotocol/nearcore/pull/1531
