### ISSUE TITLE
[TEST][bug] Error running ./start-stakewars.py

### ISSUE THREAD

**Issue by stakehost** [nearprotocol/stakewars#20]
**Describe the bug or test**
Unable to run ./scripts/start_stakewars.py script as per instructions.

**To Reproduce**
1. Run `./scripts/start-stakewars.py --init --account-id=stakehost --signer-keys`
2. Copy in `account.csv` into `~/.near`
3. Run `./scripts/start-stakewars.py --acount-id=stakehost`

**Expected behavior OR Outcome of test**
Node should run!

**Actual outcome**
```
./start_stakewars.py --account-id=stakehost
****************************************************
* Running NEAR validator node for Stake Wars *
****************************************************
Creating genesis...
Genesis created
Starting NEAR client and Watchtower dockers...
Error response from daemon: No such container: watchtower
Error: No such container: watchtower
Error response from daemon: No such container: nearcore
Error: No such container: nearcore
docker: Error response from daemon: driver failed programming external connectivity on endpoint nearcore (4e60407d2ebf6c0f607b7a9b7c00c188225a703a7055956e8a1dc9c833213218):  (iptables failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 24567 -j ACCEPT: iptables: No chain/target/match by that name.
 (exit status 1)).
Traceback (most recent call last):
  File "./start_stakewars.py", line 35, in <module>
    start_stakewars(args.home, not args.debug, nodocker, args.image, args.verbose)
  File "/data/near/nearcore/scripts/nodelib.py", line 287, in start_stakewars
    run_docker(image, home, '', verbose)
  File "/data/near/nearcore/scripts/nodelib.py", line 139, in run_docker
    envs + [image])
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['docker', 'run', '-d', '-p', u'3030:3030', '-p', u'24567:24567', '-v', '/root/.near/:/srv/near', '-v', '/tmp:/tmp', '--ulimit', 'core=-1', '--name', 'nearcore', '--restart', 'unless-stopped', '-e', 'BOOT_NODES=', 'nearprotocol/nearcore:stakewars']' returned non-zero exit status 125
```

**Specs (please complete the following information):**
 - OS: Ubuntu 18.04
- Which cloud / on-premise:  Physical/Dedicated
- CPU: 2x Xeon
- RAM: 64GB
- Disk space: 2TB
- Docker 19.03.4

**Comment by stakehost** [comment]
This appears to be because `start_stakewars` in nodelib.py calls `docker_run()` directly, without ensuring the images are downloaded - in contrast to `setup_and_run()` which both start_testnet.p` and `start_localnet.py` call.

In this instance, a machine which has not had `start_testnet.py` or `start_localnet.py` run, or  `setup_and_run()` called by some other means will not have the images required to run the stakewars net.

**Comment by ailisp** [comment]
Yeah the `EDIT` seems correct. I found this in your error message:
```
(iptables failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 24567 -j ACCEPT: iptables: No chain/target/match by that name
```
Is you firewall settings disallow opening 24567 port?

**Comment by bowenwang1996** [comment]
Looks like this is a configuration issue rather than a real bug. Please let me know if this is not the case.
