### ISSUE TITLE
[BUG] 23 validators throw out

### ISSUE THREAD

**Issue by zavodil** [nearprotocol/stakewars#215]
**Describe the bug or test**
May 20 10:32:30.745  INFO stats: # 5612819 5xUmKT6XWEyxaaV8abzvaFpgD4FeU6uMrwCRruAHs6nU **V/58** 34/33/40 peers ⬇️ 129.3kiB/s                                                                                                                      ⬆️ 266.9kiB/s 0.50 bps 0 gas/s CPU: 15%, Mem: 807.1 MiB
May 20 10:32:40.748  INFO stats: # 5612830 8qC3ptTgY1333K5gf213CvQELSMuiJ7xe5FLz93RXy4q **-/35** 34/33/40 peers ⬇️ 138.4kiB/s                                                                                                                      ⬆️ 250.3kiB/s 1.00 bps 41.96 Ggas/s CPU: 15%, Mem: 807.4 MiB 

2 my nodes lost validator status; 1 created new stake after a hardfork, second didn't create.

I saw locked tokens on both nodes but didn't see them in validators / next validators / proposals lists

**Comment by jimmy3dita** [comment]
Are you using the staking pool, or the `near stake` command?

**Comment by zavodil** [comment]
it were 2 nodes with `near stake`
