### ISSUE TITLE
Validator stats tracking

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/stakewars#224]
For the purpose of tracking stakewars participants, we would like to have a way of munching stats about validators over the period of a week. More specifically, the information we need right now, for each validator, is:
* Number of blocks produced
* Number of blocks expected

This information is fully available through the validator rpc endpoint, but we need a way of indexing the data similar to explorer backend.

**Comment by bowenwang1996** [comment]
@frol @khorolets

**Comment by frol** [comment]
I am scheduling this task for an external contributor with a deadline of 48h for the backend and a slightly relaxed deadline for some UI.

**Comment by bowenwang1996** [comment]
Thanks frol!

**Comment by jimmy3dita** [comment]
Please post here the results, so I can properly apply the right tag

**Comment by frol** [comment]
The initial work is done and the task is finally clear with all the fine details (I failed to communicate it properly from the first try). I split the task into two steps:

1. Data collection service
2. Data analysis tool (CLI at the first step)

@jimmy3dita Do we plan to show the scoreboard online or we just need to have this information for the "internal" use?

As to the representation part, I can see the following solutions:

* auto-generate and update README.md in stakewars repo (send via PR or direct push)
* auto-generate GitHub Pages with the scoreboard
* full-blown WebUI

**Comment by bowenwang1996** [comment]
We do want to show scoreboard online but it doesn't have to be fancy. We can literally use some form to do it and it's fine if the service just dumps data in csv format.

**Comment by frol** [comment]
The raw data is now collected to: https://github.com/frol/near-validators-scoreboard/tree/scoreboard

It is configured as a cron job on Render to produce those static JSON files of the validator stats for the last block in every epoch. I will add the scoreboard CSV and JSON generation once the code is PRed by the author (during the weekend). CSV is nicely viewable on GitHub, and JSON can be easily sourced into WebUI if necessary.

**Comment by bowenwang1996** [comment]
@frol I checked some json there and it doesn't look like aggregated data but rather looks like data from a single epoch. Is that the case?

**Comment by frol** [comment]
@bowenwang1996 It is by design. The aggregation script is in progress, read the README if you want to get better understanding: https://github.com/frol/near-validators-scoreboard (specifically, "Data Analysis" section; NOTE: it is probably better to rename it to aggregation instead of analysis)

**Comment by frol** [comment]
Resolved: https://github.com/frol/near-validators-scoreboard/tree/scoreboard

See the `validators_scoreboard.csv` and `validators_scoreboard.json` (two formats just for convenience). GitHub can nicely present CSV files and you can even filter the data. The scoreboards are sorted in descending order by the number of produced blocks.
