### ISSUE TITLE
[TEST][bug] Issue generating node, validator, signer key (possible AWS issue)

### ISSUE THREAD

**Issue by k9thebeast** [nearprotocol/stakewars#23]
**Describe the bug or test**
Trying to run `sudo ./scripts/start_stakewars.py --init --account-id=<your_account_id>` to generate the 3 needed keypairs

**To Reproduce**
1. Go to 'https://github.com/nearprotocol/stakewars' and follow the guide
2. Reach the initialization step, run

`sudo ./scripts/start_stakewars.py --init --account-id=<your_account_id>` 

or 

`sudo ./scripts/start_stakewars.py --init --signer-keys --account-id=<your_account_id>`

3. View contents of file in `~/.near/`

![image](https://user-images.githubusercontent.com/1131656/68169589-975d7980-ff21-11e9-82a7-0368c1da67fd.png)

4. Files are all empty!

**Expected behavior OR Outcome of test**
Files should have keys in them... something is going on in `https://github.com/nearprotocol/nearcore/blob/master/scripts/nodelib.py`

**Specs (please complete the following information):**
 - OS: Ubuntu 18.04
- Which cloud / on-premise:  AWS (@bowenwang1996 mentioned this may be an AWS specific issue)
- CPU: 8
- RAM: 32GB
- Disk space: 100GB

**Additional context**
Docker is running
![image](https://user-images.githubusercontent.com/1131656/68169949-cf18f100-ff22-11e9-9319-11bfb5334606.png)

**LMK if you want to log into my node to test**

**Comment by sweetpotatoz** [comment]
run
which python 
python --version
to see your python location and version

**Comment by sweetpotatoz** [comment]
try insert python3 like below
sudo python3 ./scripts/start_stakewars.py --init --signer-keys --account-id=<your_account_id>

**Comment by k9thebeast** [comment]
Hmm, it seems I am using a version of python2 instead of 3 to generate the keys

![image](https://user-images.githubusercontent.com/1131656/68259604-24223900-ffef-11e9-889b-a5eafc260157.png)

I ran your command but it doesn't seem to generate them. I still get empty files with no keys in them

**Comment by sweetpotatoz** [comment]
your ubuntu should have python3 as well, try "which python3"

**Comment by k9thebeast** [comment]
I do have python3 installed, but running the script with it not change anything

**Comment by sweetpotatoz** [comment]
have you tried insider nearcore folder run 
git pull 
to get the latest script

**Comment by k9thebeast** [comment]
unfortunately I have, I am up to date. Will be trying on a `gcloud` instance later today

**Comment by ailisp** [comment]
This looks very weird. I'm going to try on an aws instance soon

**Comment by ailisp** [comment]
python2 should be fine. I use system default python to run, which is python2

**Comment by k9thebeast** [comment]
@ailisp @sweetpotatoz 

It was that I was just doing `vim`... permission was denied viewing the file - did `sudo vim ...` and I was able to view it correctly. Perhaps something
