### ISSUE TITLE
[TEST][bug]Resolved!--- "No such file or directory" error when runing without docker

### ISSUE THREAD

**Issue by hoekevin** [nearprotocol/stakewars#24]
**Describe the bug or test**
After runing command:  ./scripts/start_stakewars.py --nodocker
OSError:[Errno 2]["No such file or directory" error when runing without docker

when run "start_stakewars.py --nodocker" first time , the cargo build does not work properly.
the "near" file in ~/nearcore/target/release folder has not been generated, which cause "No such file" error.

### **Solution:**
run command line in ~/nearcore directory: cargo build --release -p near
then the "near"file will be generated correctly and then your node can be started normally!

**Comment by ailisp** [comment]
cargo is likely not invoked. Can you quickly try running 
```python
import subprocess
subprocess.run(['cargo'])
```
and see if it gives error?

**Comment by hoekevin** [comment]
it was not an error of cargo path,cargo can be runned on  any folder. some other persons had the same error and have resolved them by my instuction.

new Near version have fix this bug

**Comment by ailisp** [comment]
Cool. Thanks for confirming!
