### ISSUE TITLE
[TEST][bug] (Resolved)near launch error when run with docker

### ISSUE THREAD

**Issue by hoekevin** [nearprotocol/stakewars#25]
**Describe the bug or test**
start node by run: `root@file:~/nearcore# ./scripts/start_stakewars.py`
an error occured:
`[2019-11-05T14:25:16Z INFO  near] Opening store database at "/srv/near/data"
/usr/local/bin/run.sh: line 24:    24 Illegal instruction     (core dumped) near --home=${NEAR_HOME} run --boot-nodes=${BOOT_NODES}`

`*** /usr/local/bin/run.sh exited with status 132.`
`*** Shutting down runit daemon (PID 19)...`
`*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...`
`Nov  5 14:25:17 e054486da90c syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
*** Killing all processes...`

To find what cause the error,I enter the docker container :

`root@file:~/nearcore# docker run -ti -v /root/.near:/srv/near -v /tmp:/tmp -p 24567:24567 -p 3030:3030 6537accf533c /bin/bash`

In the container , I run the command:`root@62286e684a59:/# near --home /srv/near run`
The same error " Illegal instruction "

`[2019-11-05T14:22:20Z INFO  near] Opening store database at "/srv/near/data"
Illegal instruction (core dumped)`

**Specs (please complete the following information):**
 - OS:Ubuntu 18.04.1 LTS bionic 
- CPU: XEON E7
- RAM: 32G
- Disk space:2T

**Comment by hoekevin** [comment]
by running local compiled "near" program(in local folder:~/nearcore/target/release) in nearcore container, this problem can be resolved! It mostly due to Incompatible CPU instruction set。

**Comment by ailisp** [comment]
@hoekevin we're likely fixed this in our docker builds too in https://github.com/nearprotocol/nearcore/pull/1664. Can you confirm since we don't have an older cpu? Thanks

**Comment by hoekevin** [comment]
ok, i will try and reply you

**Comment by hoekevin** [comment]
sorry,I have tried but the bug was not fixed.

**Comment by hoekevin** [comment]
> @hoekevin we're likely fixed this in our docker builds too in [nearprotocol/nearcore#1664](https://github.com/nearprotocol/nearcore/pull/1664). Can you confirm since we don't have an older cpu? Thanks
ok, i will try and reply you
