### ISSUE TITLE
Staking contract problem and other questions

### ISSUE THREAD

**Issue by Anonstake** [nearprotocol/stakewars#251]
Hello! 

We deployed our staking contract (“anonstake”) yesterday and everything worked like a charm, kudos to the dev team! 

The staking contract has 3 delegators and the balance was more than the seat price. This was yesterday at 5pm UTC:
near@server:~$ near validators next| grep "seat price"
Next validators (total: 71, seat price: 56,648)

The proposal was accepted:
near proposals | grep anonstake
| Proposal(Accepted) | anonstake                 | 70,300             | 1       |

Today I checked my validator and it seems that it never started working/producing block. I went over logs but can't see any error/warning and the "V" never showed up:
example:
May 21 00:50:02.759  INFO stats: # 5655836 6BK6dCa2ieFCHoNFQgJFyYXneuAsRRAjGB3HCar11DSA -/76 35/34/40 peers ⬇ 182.0kiB/s ⬆ 180.5kiB/s 1.00 bps 0 gas/s CPU: 14%, Mem: 1.1 GiB

Now all the delegated tokens are unlocked at staking contract account. How can I restake/lock tokens again? Should it be done with the owner account?

I also have a few additional questions:

- I played around with staking contract last week and I deployed staking contract on my original account (anonstake.test) with which I signed for stake wars. Is this a problem, did it change anything related to the account functionality or security?
- I would like to automate upgrade and I didn’t find any info if the hard folk is always at the same time( 5pm pacific?) or is based on block height, etc..?
- Is “near validator  <epoch>” the only way to see validator metrics? Is there a prometheus source or something similar in the works?
- Can you tell more about the leaderboard? What is taken into account for points?
- Should I update VALIDATORS.md with my staking contract account now that the contract is live?

I wish you all a good day and thanks for your time!

**Comment by Anonstake** [comment]
I am again present in the proposal list:
near@server:~$ near proposals | grep anonstake
| Proposal(Accepted) | anonstake                 | 70,200             | 1       |

Will monitor if I become active validator.

**Comment by Anonstake** [comment]
Still the same issue. I get into validator set, but validator is not producing blocks:
near@server:~$ near validators current | grep anonstake
| anonstake             | 70,200  | 1       | 0%       |               0 |               2 |

**Comment by bowenwang1996** [comment]
It is likely that you used the wrong staking key. When you initialize the staking contract, you need to pass in a `stake_public_key` and this should be the same as the public key in `validator_key.json` on your node.

**Comment by Anonstake** [comment]
I double-checked and the stake public key is the right one. Its the same as the one in ./near/betanet/validator_key.json. I did pass it in full (with ed25519), should I use it without ed25519?

**Comment by bowenwang1996** [comment]
In that case check that the account id in `validator_key.json` matches the account id of the staking contract.

**Comment by Anonstake** [comment]
I solved it, thanks. I was passing a wrong public stake key, same as I used for my current validator. 

For everyone that are already running validators, when switching to validating with staking contract, you should (backup) & remove ./near directory and rerun nearup command to create new validator key for your staking contract. If you used the wrong validator key when calling the staking contract, you can use to update the staking public key:
_near call <validator_id> update_staking_key '{"staking_public_key": "PUBLIC_KEY"}' --accountId <ownerId>_
to set new public stake key for your contract -> use the one create in the nearup. Is this correct @bowenwang1996 ?

**Comment by bowenwang1996** [comment]
Yes. But I think it is better to update staking public key than to delete `~/.near`, as the latter means you have to resync your node.
