### ISSUE TITLE
[BUG|FEATURE] We burn tokens if we SEND them to the staking-pool contract

### ISSUE THREAD

**Issue by zavodil** [nearprotocol/stakewars#262]
**Describe the bug or test**
Someone SENT tokens to my staking pool contract instead of delegate them.

That's is, user can't reach tokens anymore

I don't believe it will be a unique issue.

Solution: update smart contract and revert all send transactions from users who are not an owner

**Comment by bowenwang1996** [comment]
It is an issue. Your solution only works if you have a full access key to the smart contract, which shouldn't be the case in production. I am not sure what the best way to prevent this is.
cc @kcole16.

**Comment by kcole16** [comment]
The best way I can think to handle it is to include something like the Solidity fallback function: https://solidity.readthedocs.io/en/v0.5.3/contracts.html#fallback-function

Basically, if NEAR is transferred to an account with a contract and defined fallback function, the fallback function is executed, which in this case would involve transferring the NEAR back to the sender, or routing it into `deposit`.

No clue how feasible this is to implement though: cc @evgenykuzyakov

**Comment by bowenwang1996** [comment]
@kcole16 I don't think it is feasible to implement this without significant change. Contracts don't have the ability to react when they receive token transfers. Adding that would involve significant change in the runtime. Also with this fallback function does it mean that users cannot transfer tokens to a contract? There are legitimate use cases of that.

**Comment by kcole16** [comment]
Yes, users can transfer tokens to contracts with fallback function. 

It's useful because, without one, all transfers that aren't function calls are rejected (no accidental transfers), and you can execute any arbitrary code in the function, e.g. users can just transfer NEAR to a validators account and the fallback function would trigger `deposit` and `stake`.

**Comment by bowenwang1996** [comment]
> all transfers that aren't function calls are rejected

I see. That is a change that we can potentially make. @evgenykuzyakov what do you think?

**Comment by htafolla** [comment]
I opened a bug on the contract git a few days back. https://github.com/near/initial-contracts/issues/24 not sure how to combine them.

**Comment by jimmy3dita** [comment]
Will move the discussion there then
