### ISSUE TITLE
[TEST][ Dangerous ] unpredictable errors may be caused by Cross platform compilation.

### ISSUE THREAD

**Issue by hoekevin** [nearprotocol/stakewars#28]
# Running `near` program compiled in a single CPU platform on DOCKER of different CPU platforms may lead to unpredictable errors!

These days, I have been looking for the reason of the errors mentioned in issues #25  and finally  I found that the problem lies in the incompatible CPU platform instruction set .
As mentioned in issues #25, there will be   `illegal instruction errors`  when I  runs the `nearcore` with docker. Now I can confirm that It was caused by  incompatible instruction sets between  my  CPU platform and the platform on where `near` was compiled.

In order to prove my idea, I mapped the locally compiled `near` program into the container of `nearcore` and tried to run it. It turned out that everything was OK. I was right.

### map local near program into container:
`root@file:~# docker run -ti  -v /root/.near:/srv/near -v ~/nearcore/target/release:/testnear 6537accf533c  /bin/bash` 
### local folder ` ~/nearcore/target/release` mapped into container folder `/testnear` 
`root@247329f6a649:/# cd testnear`
`root@247329f6a649:/testnear# ls`
`build  deps  examples  genesis-csv-to-json  genesis-csv-to-json.d  incremental  libnear.d  libnear.rlib  native  near  near.d`

### error occured when run `near` in the PATH of container OS
`root@247329f6a649:/testnear# near --home /srv/near run`
`[2019-11-07T12:10:09Z INFO  near] Opening store database at "/srv/near/data"
Illegal instruction (core dumped)`

### node startup normally when run `near` in the folder /testnear which was compiled locally.
`root@247329f6a649:/testnear# ./near --home /srv/near run`
`[2019-11-07T12:10:15Z INFO  near] Opening store database at "/srv/near/data"`
`[2019-11-07T12:10:15Z INFO  near_network::peer_manager] Server listening at` `ed25519:E8zzE3DvDBxCjSp5m3SivJJ3QkEQvJhvavsMN8rxRqTz@0.0.0.0:24567`
`[2019-11-07T12:10:25Z INFO  near_client::info] #     0 Waiting for peers V/38  1/1/40 peers ⬇ 2` `B/s ⬆ 2 B/s 0.00 bps 0 gas/s CPU: 7%, Mem: 22.3 MiB`
`[2019-11-07T12:10:29Z WARN  near_network::peer] Received Sync while Connecting from` `Outbound connection.`
`[2019-11-07T12:10:35Z INFO  near_client::info] State 2: header V/38  3/1/40 peers ⬇ 8.4kiB/s` `⬆ 8.3kiB/s 0.00 bps 0 gas/s CPU: 5%, Mem: 24.8 MiB`

**Comment by bowenwang1996** [comment]
Fixed in the latest version as we specify target to be x86_64.
