### ISSUE TITLE
[I NEED TOKENS] Post here if you need stake for your validator node

### ISSUE THREAD

**Issue by jimmy3dita** [nearprotocol/stakewars#289]
If you deployed your staking pool, but you don't have enough tokens to become a validator, post its address below, so we can delegate funds to you.

What does it mean?
1. Give a look to the page [Economics of a Validator](https://docs.near.org/docs/validator/economics) on the official docs to understand how _validator seats_ are assigned
2. Use near-shell to discover the actual cost of a seat: `env NODE_ENV=betanet near validators next`

We will give priority to the new validators that didn't receive any tokens in the past weeks.

**Comment by htafolla** [comment]
BlazeNet lost it's seat this morning. I had 65k staked and lost the other 10k when I was testing the old contract. Please delegate some NEAR to me. :)

**Comment by armyids** [comment]
MasterAccount: armyid.betanet
Contract: armyid
I consider myself as a new validator because last week I tried to deploy staking pool 'armyids', but it is failed so I created the new one 'armyid'.

**Comment by only25x** [comment]
MasterAccount: only25x.betanet
Contract: only25x
New Validator

**Comment by chernopyatko** [comment]
Master account: chernopyatko.betanet
Contract: cher3
New validator

**Comment by SSergey911** [comment]
MasterAccount: equilibrium.betanet
Contract: gems
Please delegate to me for full understanding NEAR validator staking mechanism.

**Comment by blxpro** [comment]
Master Account: blxpro.betanet
Contract: blx_validator
I want to become a validator. I filled out a google form 2 weeks ago

**Comment by antonborisov87** [comment]
Master Account: karbentum.betanet
Contract: nearcool
I want to become a validator. I filled out a google form sometime ago.

**Comment by tellmeblink** [comment]
Master Account: neartest2.betanet
Contract: blink
I want to become a validator. I filled out a google form sometime ago.

**Comment by IvanEasy** [comment]
Master Account: nearblyat.betanet
Contract:blyatt
I want to become a validator. I filled out a google form sometime ago.

**Comment by loiron** [comment]
Master Account: gzch.betanet
Contract: gzchpool
I want to become a validator. I filled out a google form sometime ago.

**Comment by cheoa** [comment]
Master Account: cheoa.betanet
Contract: che1
I want to become a validator. I filled out a google form some days ago.

**Comment by jukblr1991** [comment]
Master Account: kvasik.betanet
Contract: kvasnear
I want to become a validator. I filled out a google form sometime ago.

**Comment by decemtk** [comment]
Master Account: aalex.betanet
Contract: aalex
My old contract is alexz01,I have initialized the contract with the wrong owner. In that case I  have to deploy a new contract.Please delegate to me . Thanks very much.

**Comment by aptemuyc** [comment]
Master Account: aptemuyc.betanet
Contract: aptemuyccc
I want to become a validator. I filled out a google form sometime ago.please charge tokens, thanks

**Comment by breeze158** [comment]
Master Account: breeze.betanet
Contract: a_breeze
I'd like to become a validator. I create a PR sometime ago. Could you delegate to me please? thanks

**Comment by ilblackdragon** [comment]
Whoever here have not received standard 75k betanet NEAR tokens before - should have received them just now. Let us know in the https://near.chat if you have any issues still.
