### ISSUE TITLE
[BREAK - P1][epic] near-shell crashed on Ubuntu

### ISSUE THREAD

**Issue by marco-sundsk** [nearprotocol/stakewars#29]
**Describe the epic break you found or epic contract you've created**
near-shell version 0.14.0 crashed when trying to new_project with an Error:
Error: Cannot find module '/usr/local/bin/cli.js'
**To Reproduce**
1. npm -g install npm
2. npm -g install near-shell
3. near new_project stakewars
4. See : Error: Cannot find module '/usr/local/bin/cli.js'

**Expected behavior OR Outcome of work**
Clearly it should create a dir as it does in version 0.11.x

**Specs (please complete the following information):**
 - OS: Ubuntu 18.04
- Which cloud / on-premise:  AliYun
- CPU: Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
- RAM: 4G
- Disk space: 500G SSD

**Additional context**
npm version: 6.13.0
near-shell version: 0.14.0
And I found this cli.js in this path: 
/usr/local/lib/node_modules/near-shell/bin/cli.js
And If I run near with full origin path (not the linker one in /usr/local/bin), it seems OK:

```
root@buildlinks-test-platform:~/near_stakewars# /usr/local/lib/node_modules/near-shell/bin/near  new_project stakewars
[WARNING] Didn't find config at /root/near_stakewars/src/config, using default shell config
{
  networkId: 'default',
  nodeUrl: 'https://rpc.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.nearprotocol.com'
}
```

**Screenshots Optional**

```
root@buildlinks-test-platform:~/near_stakewars# near new_project stakewars
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module '/usr/local/bin/cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by janedegtiareva** [comment]
This might be fixed in 0.14.2.
