### ISSUE TITLE
Create Account Error in online wallet

### ISSUE THREAD

**Issue by marco-sundsk** [nearprotocol/stakewars#31]
**Describe the bug or test**
When create a new account, first it says ok, your id is available, but when click Create, after a while, it says "Username is taken. Try something else.". And some error msg showed in validator node.

**How to Reproduce**
1. Go to online wallet
2. Add some account
3. click Create
4. wait a while, it will show "Username is taken. Try something else."

**Expected behavior OR Outcome of test**
Clearly, the name is not occupied, the creation should success.

**Specs (please complete the following information):**
 - OS: Ubuntu 18.04
- Which cloud / on-premise:  AliYun
- CPU: Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
- RAM: 4G
- Disk space: 500G SSD

**Additional context**
**Screenshots Optional**
![bug2](https://user-images.githubusercontent.com/47070476/68726989-1cb9eb80-05fe-11ea-92d2-a9dbcde26322.png)

![bug1](https://user-images.githubusercontent.com/47070476/68726942-f8f6a580-05fd-11ea-9b03-300eaa04a473.png)

**Comment by vgrichina** [comment]
I'm able to reproduce on https://wallet.tatooine.nearprotocol.com/create/

 "Username is taken. Try something else." is use a catch all for multiple different errors. This one looks like `nearcore` isn't performing properly:

> Error: send_tx_commit has timed out

is underlying error on nearcore side.

**Comment by bowenwang1996** [comment]
I think we do have some issues in rpc right now that might cause wallet to be nonfunctional at times. I'll look into this.

**Comment by vgrichina** [comment]
@bowenwang1996 we probably need to add `send_tx_commit has timed out` into some FAQ / triage guide, as it's pretty common underlying issue.

**Comment by k9thebeast** [comment]
Just took a video of myself trying as well

https://www.dropbox.com/s/wixecbru9zilamk/EyuBkg1xrN.mp4?dl=0

**Comment by joesixpack** [comment]
I ran into this problem too when going directly to the web.

But using the URL with my public key provided when trying to stake via near shell results in the username being accepted, but thereafter results in a "missing public key for tatooine" error.

Seems like the login redirects to create, because it can't find the public key.
