### ISSUE TITLE
NODE CRASH caused by a sudden memory and cpu soar

### ISSUE THREAD

**Issue by marco-sundsk** [nearprotocol/stakewars#32]
**Describe the bug or test**
At height 34905, usage of mem and cpu both soar, cpu from 4% to 100%, mem from 0.39G to 4G and cause a oomkiller process. After auto restart, node then halt at heigh 34914, and say: Received Sync while Connecting from Outbound connection. 
And finally, node stuck at 35002, and says Downloading headers 100%.

**How to Reproduce**
1. Happened at 2019-11-13T06:35:29
2. see screen shot for detail info 

**Expected behavior OR Outcome of test**
running smoothly.

**Specs (please complete the following information):**
 - OS: Ubuntu 18.04
- Which cloud / on-premise:  AliYun
- CPU: Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
- RAM: 4G
- Disk space: 500G SSD

**Additional context**

**Screenshots Optional**
first shot:
![bug3](https://user-images.githubusercontent.com/47070476/68742643-a2a05b80-062b-11ea-9e49-3f90372831dd.png)

after auto restart:
![bug4](https://user-images.githubusercontent.com/47070476/68742658-afbd4a80-062b-11ea-87e6-d8e1a8c7c93e.png)

at some point of restarting, it shows different:
![bug5](https://user-images.githubusercontent.com/47070476/68742698-cc598280-062b-11ea-8d8e-893fae339c4c.png)

finally:
![bug6](https://user-images.githubusercontent.com/47070476/68742840-1c384980-062c-11ea-9167-29e518047343.png)

**Comment by bowenwang1996** [comment]
The bug is fixed in https://github.com/nearprotocol/nearcore/pull/1688
