### ISSUE TITLE
[TEST][bug] Node Stuck 

### ISSUE THREAD

**Issue by stakery** [nearprotocol/stakewars#33]
**Describe the bug or test**

2019-11-13T06:53:09 -- At height 35308, downloading blocks 99%:
`memory allocation of 144703488 bytes failed/usr/local/bin/run.sh: line 25:    25 Aborted                 (core dumped) near --home=${NEAR_HOME} run --telemetry-url=${TELEMETRY_URL} --boot-nodes=${BOOT_NODES}`

2019-11-13T06:54:33 -- After that, switch to 35315, downloading blocks 99%:
`[2019-11-13T06:55:30Z ERROR near_client::client_actor] State sync received hash 3W6qSJG8Q1n3voj8X8YHfuDRA4Y2hA2Qro6rcFKRCeLD that we're not expecting, potential malicious peer`

2019-11-13T06:55:33 -- 35315 Downloading headers 100%, followed by many more errors of:
`[2019-11-13T06:55:30Z ERROR near_client::client_actor] State sync received hash 3W6qSJG8Q1n3voj8X8YHfuDRA4Y2hA2Qro6rcFKRCeLD that we're not expecting, potential malicious peer`

2019-11-13T06:55:52 -- as well as:
`[2019-11-13T06:55:52Z ERROR near_client::sync] State sync: state download for shard 0 timed out in 10 seconds`
`[2019-11-13T06:55:52Z ERROR near_client::sync] State sync: state download for shard 2 timed out in 10 seconds`
`[2019-11-13T06:55:52Z ERROR near_client::sync] State sync: state download for shard 4 timed out in 10 seconds`
`[2019-11-13T06:55:52Z ERROR near_client::sync] State sync: state download for shard 5 timed out in 10 seconds`

2019-11-13T07:06:13 -- after which the node finally stuck at 
`35418 4Mpe2kB6EiojwdFgW2FC29hXek6QK8oFJydwQMiS3VTw V/11  4/3/40`

**How to Reproduce**
Core dump happened at 2019-11-13T06:53:09

**Expected behavior OR Outcome of test**
Network continuance

**Specs:**
 - OS: Ubuntu 18.04.3 LTS
- Cloud: Custom
- CPU: 2 Cores
- RAM: 12 GB
- Disk space: 100 GB

**Additional context**

Found additional core dump at 2019-11-13T06:39:34, followed by hundreds of warnings of:

`[2019-11-13T06:41:19Z WARN  near_network::peer] Received Block while Connecting from Outbound connection.`

**Comment by bowenwang1996** [comment]
We already fixed in bug in https://github.com/nearprotocol/nearcore/pull/1688
