### ISSUE TITLE
"nearshell creating configuration params folder on current directory" may cause users to be confused

### ISSUE THREAD

**Issue by hoekevin** [nearprotocol/stakewars#34]
nearshell always creates a  folder of configuration named "neardev" on current directory after running "near login" command , when running nearshell on another folder without "neardev" folder, nearshell's login state would change to unlog, which would cause users to be confused .

**Comment by janedegtiareva** [comment]
What would be a less confusing behavior?

**Comment by janedegtiareva** [comment]
Filed an issue in near-shell https://github.com/nearprotocol/near-shell/issues/198
