### ISSUE TITLE
[Choose one --> BUG | TEST] ...

### ISSUE THREAD

**Issue by fierydev1** [nearprotocol/stakewars#357]
**Describe the bug or test**
I'm trying to install validator node on below mentioned config!
**How to Reproduce**

root@DESKTOP-I9V6R7R:~# near login --account_id fierydev-1.betanet
Using options: {
  accountId: 'fierydev-1.betanet',
  networkId: 'betanet',
  nodeUrl: 'https://rpc.betanet.near.org',
  contractName: undefined,
  walletUrl: 'https://wallet.betanet.near.org',
  helperUrl: 'https://helper.betanet.near.org',
  initialBalance: null
}

Please authorize NEAR Shell on at least one of your accounts.

If your browser doesn't automatically open, please visit this URL
https://wallet.betanet.near.org/login/?title=NEAR+Shell&public_key=ed25519%3AGpy6JXF5t928XoJPuWCiB3VutVv89ExZcGx7gcPvVWb&success_url=http%3A%2F%2F127.0.0.1%3A5000
Please authorize at least one account at the URL above.

Which account did you authorize for use with NEAR Shell?
Enter it here (if not redirected automatically):

   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │    NEAR Shell has a minor update available 0.23.2 → 0.24.1     │
   │   Run npm install -g near-shell to avoid unexpected behavior   │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd.exe',
  path: 'cmd.exe',
  spawnargs: [
    '/s',
    '/c',
    'start',
    '""',
    '/b',
    'https://wallet.betanet.near.org/login/?title=NEAR+Shell&public_key=ed25519%3AGpy6JXF5t928XoJPuWCiB3VutVv89ExZcGx7gcPvVWb&success_url=http%3A%2F%2F127.0.0.1%3A5000'
  ]
}

**Expected behavior OR Outcome of test**
Unable to login via
near login

https://explorer.betanet.near.org/transactions/CHuzcyt4mtTLNYZY455FALgst31P6M5tQeatREVn3Wsv

Key was added successfully above

**Specs (please complete the following information):**
 - OS: Linux 18.04 running on Win 10x64 via WSL
- Which cloud / on-premise: On premise
- CPU: Ryzen 3900X
- RAM: 32GB
- Disk space: 1TB

**Additional context**

**Screenshots Optional**
[Dump.txt](https://github.com/nearprotocol/stakewars/files/4692716/Dump.txt)

**Comment by bowenwang1996** [comment]
It's probably a node version issue. Make sure that your nodejs version is at least 12.

**Comment by fierydev1** [comment]
root@DESKTOP-I9V6R7R:~# node -v
v12.17.0

**Comment by fierydev1** [comment]
Does that help?
As it might be evident, I'm not a developer 😬

**Comment by bowenwang1996** [comment]
What is your near-shell version?

**Comment by fierydev1** [comment]
Can you help me with what command can tell me that?

**Comment by fierydev1** [comment]
NEAR Shell has a minor update available 0.23.2 → 0.24.1
This was a part of my dump

**Comment by fierydev1** [comment]
Someone on discord had tried getting it to run, but latest version was giving issues.... So the following was the error:

fierydev@DESKTOP-I9V6R7R:~$ node -v
v12.17.0
fierydev@DESKTOP-I9V6R7R:~$
Installing nearshell now!
Forgot sudo
Trying again
So does this look ok?
fierydev@DESKTOP-I9V6R7R:~$ sudo npm install -g near-shell
[sudo] password for fierydev:
/usr/local/bin/near -> /usr/local/lib/node_modules/near-shell/bin/near

node-hid@1.2.0 install /usr/local/lib/node_modules/near-shell/node_modules/node-hid
prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, mkdir '/usr/local/lib/node_modules/near-shell/node_modules/node-hid/build'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/near-shell/node_modules/node-hid/build'
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/near-shell/node_modules/node-hid
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

usb@1.6.3 install /usr/local/lib/node_modules/near-shell/node_modules/usb
prebuild-install --verbose || node-gyp rebuild
usb@1.6.3 install /usr/local/lib/node_modules/near-shell/node_modules/usb
prebuild-install --verbose || node-gyp rebuild

prebuild-install info begin Prebuild-install version 5.3.4
prebuild-install info looking for cached prebuild @ /home/fierydev/.npm/_prebuilds/f5a2d7-usb-v1.6.3-node-v72-linux-x64.tar.gz
prebuild-install http request GET https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v72-linux-x64.tar.gz
prebuild-install http 200 https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v72-linux-x64.tar.gz
prebuild-install info downloading to @ /home/fierydev/.npm/_prebuilds/f5a2d7-usb-v1.6.3-node-v72-linux-x64.tar.gz.22306-eac8943aafdb3.tmp
prebuild-install info renaming to @ /home/fierydev/.npm/_prebuilds/f5a2d7-usb-v1.6.3-node-v72-linux-x64.tar.gz
prebuild-install info unpacking @ /home/fierydev/.npm/_prebuilds/f5a2d7-usb-v1.6.3-node-v72-linux-x64.tar.gz
prebuild-install WARN install EACCES: permission denied, mkdir '/usr/local/lib/node_modules/near-shell/node_modules/usb/build'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/near-shell/node_modules/usb/build'
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/near-shell/node_modules/usb
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-hid@1.2.0 (node_modules/near-shell/node_modules/node-hid):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-hid@1.2.0 install: prebuild-install || node-gyp rebuild
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.3 (node_modules/near-shell/node_modules/usb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.3 install: prebuild-install --verbose || node-gyp rebuild
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ near-shell@0.24.1
added 229 packages from 176 contributors in 36.294s

**Comment by fierydev1** [comment]
root@DESKTOP-I9V6R7R:~# sudo npm install -g near-shell@0.24.1
/usr/local/bin/near -> /usr/local/lib/node_modules/near-shell/bin/near

> node-hid@1.2.0 install /usr/local/lib/node_modules/near-shell/node_modules/node-hid
> prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, mkdir '/usr/local/lib/node_modules/near-shell/node_modules/node-hid/build'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/near-shell/node_modules/node-hid/build'
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/near-shell/node_modules/node-hid
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> usb@1.6.3 install /usr/local/lib/node_modules/near-shell/node_modules/usb
> prebuild-install --verbose || node-gyp rebuild

prebuild-install info begin Prebuild-install version 5.3.4
prebuild-install info looking for cached prebuild @ /home/fierydev/.npm/_prebuilds/f5a2d7-usb-v1.6.3-node-v72-linux-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ /home/fierydev/.npm/_prebuilds/f5a2d7-usb-v1.6.3-node-v72-linux-x64.tar.gz
prebuild-install WARN install EACCES: permission denied, mkdir '/usr/local/lib/node_modules/near-shell/node_modules/usb/build'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/near-shell/node_modules/usb/build'
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/near-shell/node_modules/usb
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-hid@1.2.0 (node_modules/near-shell/node_modules/node-hid):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-hid@1.2.0 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.3 (node_modules/near-shell/node_modules/usb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.3 install: `prebuild-install --verbose || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ near-shell@0.24.1
updated 1 package in 24.855s

root@DESKTOP-I9V6R7R:~# npm install -g near-shell@0.23.2
/usr/local/bin/near -> /usr/local/lib/node_modules/near-shell/bin/near
+ near-shell@0.23.2
removed 28 packages, updated 2 packages and moved 11 packages in 30.926s

**Comment by fierydev1** [comment]
Hence, in the end we got near-shell@0.23.2

If I try installing latest, this happens:

fierydev@DESKTOP-I9V6R7R:~$ sudo npm install -g near-shell
[sudo] password for fierydev:
/usr/local/bin/near -> /usr/local/lib/node_modules/near-shell/bin/near

> node-hid@1.2.0 install /usr/local/lib/node_modules/near-shell/node_modules/node-hid
> prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, mkdir '/usr/local/lib/node_modules/near-shell/node_modules/node-hid/build'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/near-shell/node_modules/node-hid/build'
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/near-shell/node_modules/node-hid
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> usb@1.6.3 install /usr/local/lib/node_modules/near-shell/node_modules/usb
> prebuild-install --verbose || node-gyp rebuild

prebuild-install info begin Prebuild-install version 5.3.4
prebuild-install info looking for cached prebuild @ /home/fierydev/.npm/_prebuilds/f5a2d7-usb-v1.6.3-node-v72-linux-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ /home/fierydev/.npm/_prebuilds/f5a2d7-usb-v1.6.3-node-v72-linux-x64.tar.gz
prebuild-install WARN install EACCES: permission denied, mkdir '/usr/local/lib/node_modules/near-shell/node_modules/usb/build'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/near-shell/node_modules/usb/build'
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/near-shell/node_modules/usb
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-hid@1.2.0 (node_modules/near-shell/node_modules/node-hid):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-hid@1.2.0 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.3 (node_modules/near-shell/node_modules/usb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.3 install: `prebuild-install --verbose || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ near-shell@0.24.1
updated 1 package in 31.251s

**Comment by bowenwang1996** [comment]
@mikedotexe can you take a look? Looks like a windows issue.

**Comment by fierydev1** [comment]
I believe so. Thanks for taking a look.

**Comment by fierydev1** [comment]
So since this wasn't working, I have now taken an Ubuntu Server for this!
