### ISSUE TITLE
near-shell can use postfix to simplify big number param 

### ISSUE THREAD

**Issue by marco-sundsk** [nearprotocol/stakewars#36]
**Describe the bug or test**
In near stake cmd, 
near stake \<account_id\> \<PK\> \<staking amount\>
we should put a big number for staking amount, usually include 18 zeros.
I strongly suggest we can use 30k for 30,000,  30m for 30,000,000, 30g for 30,000m, and so on.
Then If we want to stake 10 Near, I can put 10e for 10 followed by 18 zeros.
Here is the list:
- 1KB = 1024 B,     	K for 3 zero
- 1 MB = 1024KB,	M for 6 zero
- 1 GB = 1024 MB, 	G for 9 zero
- 1 TB = 1024 GB, 	T for 12 zero
- 1 PB = 1024 TB, 	P for 15 zero
- 1 EB = 1024 PB, 	E for 18 zero

**How to Reproduce**
This is a suggestion.

**Expected behavior OR Outcome of test**
As described in first section.

**Specs (please complete the following information):**
 - OS: Ubuntu 18.04
- Which cloud / on-premise:  AliYun
- CPU: Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
- RAM: 4G
- Disk space: 500G SSD

**Additional context**
N/A

**Screenshots Optional**
N/A

**Comment by janedegtiareva** [comment]
Existing issue in near-shell https://github.com/nearprotocol/near-shell/issues/113
