### ISSUE TITLE
Block Production Tracking Delay

### ISSUE THREAD

**Issue by joesixpack** [nearprotocol/stakewars#37]
j@j-desktop:~/nearcore$ RUST_BACKTRACE=full ./scripts/start_testnet.py --nodocker
****************************************************
* Running NEAR validator node for Official TestNet *
****************************************************
cargo 1.40.0-nightly (8b0561d68 2019-09-30)
    Finished release [optimized] target(s) in 0.15s
Using existing node configuration from /home/j/.near/ for testnet
Stake for user 'joesixpack' with '[deleted]'
Starting NEAR client...
Autoupdate is not supported at the moment for runs outside of docker
thread 'main' panicked at 'Failed to deserialize config: Error("missing field `block_production_tracking_delay`", line: 51, column: 3)', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x56087fcf970c - backtrace::backtrace::libunwind::trace::h19774dea45f5192e
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x56087fcf970c - backtrace::backtrace::trace_unsynchronized::h17947fc1cb72b217
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x56087fcf970c - std::sys_common::backtrace::_print_fmt::h7b3edf3a4bfcedd3
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x56087fcf970c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3ea3134b71160a75
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x56087f4f239c - core::fmt::write::hb50f65a11f629d84
                               at src/libcore/fmt/mod.rs:1028
   5:     0x56087fcf8f76 - std::io::Write::write_fmt::h30970d8ac223811c
                               at src/libstd/io/mod.rs:1412
   6:     0x56087fcf8bd0 - std::sys_common::backtrace::_print::h48f10c5c50d0e0d7
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x56087fcf8bd0 - std::sys_common::backtrace::print::h93ea115513ee061c
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x56087fcf8bd0 - std::panicking::default_hook::{{closure}}::hbf5672c85fe44d10
                               at src/libstd/panicking.rs:196
   9:     0x56087fcf836f - std::panicking::default_hook::h5d2ce66938b54bc6
                               at src/libstd/panicking.rs:210
  10:     0x56087fcf836f - std::panicking::rust_panic_with_hook::h60898b7fda675e17
                               at src/libstd/panicking.rs:473
  11:     0x56087fcf7e9f - std::panicking::continue_panic_fmt::h46da20a693d55410
                               at src/libstd/panicking.rs:380
  12:     0x56087fd07906 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  13:     0x56087f4ec7b9 - core::panicking::panic_fmt::h4ddf3c5f8367e071
                               at src/libcore/panicking.rs:84
  14:     0x56087f4f2996 - core::result::unwrap_failed::h5541759cb38b9dc1
                               at src/libcore/result.rs:1165
  15:     0x56087f669851 - near::config::Config::from_file::hf82d0cfb0eef19f9
  16:     0x56087f36dacd - near::main::h60e53da9b73414fc
  17:     0x56087f35e893 - std::rt::lang_start::{{closure}}::hcabdef8a38265d1e
  18:     0x56087f377cbe - main
  19:     0x7f489495eb6b - __libc_start_main
  20:     0x56087f35e7aa - _start
  21:                0x0 - <unknown>
j@j-desktop:~/nearcore$

**Comment by bowenwang1996** [comment]
This means that you are running old code or old docker image.

**Comment by joesixpack** [comment]
I found that deleting ~/.near resolved the issues.
