### ISSUE TITLE
Mention the branch for Stakewars

### ISSUE THREAD

**Issue by StakerSpace** [nearprotocol/stakewars#38]
**Describe the bug or test**
I want to validate, but always before validating, I check if there are updates on the branch. Can we update the readme on which branch the validators have to be on.

**Expected behavior OR Outcome of test**
Find in the README what branch we should be on for StakeWars as the docs of the offical website mention staging.

**Comment by potatodepaulo** [comment]
Next week we will have a `stakewars` branch which will always be correct from now on.
