### ISSUE TITLE
[TEST][benchmark] Running a node

### ISSUE THREAD

**Issue by potatodepaulo** [nearprotocol/stakewars#4]
# Hello everyone!

## Welcome to Stake Wars! (Plays unlicensed space music) Dun dun dun duuuuun!

This issue is your entry point to the competition. To get started, add a comment here with [node info] and what benchmark you ran against the node. This test is a freebie so everyone who participates can receive points.  A template for this comment is provided below. We want to know the specs of whatever you're running against (not necessarily your personal machine) and a cool benchmark. If you can't think of one, we provided some examples you can copy.

For all future bugs or tests, please create a new issue and use the [TEST], [BEND] or [BREAK] labels when you do.

## Comment Template for this P3

Machine(s) specs:
- Which cloud / on-premise
 - CPU
 - RAM
 - Disk space

Cool Benchmark:
- Can be speed, performance, scale or something we haven't seen. It just needs a unit of measurement that provides insight.
    - E.g. TPS of node when state takes 50 gb of storage
    - E.g. TPS of 10 nodes on a separate network

**Comment by hoekevin** [comment]
Machine(s) specs:

Which cloud / on-premise：personal mechine
CPU:XEON 2620
RAM :32G
Disk space:1TB

**Comment by victorxu0411** [comment]
Machine(s) specs:

personal pc
CPU: AMD Ryzen 9 3900X
RAM: 32G
Disk space:1TB

**Comment by StakerSpace** [comment]
**_**Machine Specs:**_**
**Cloud**: Contabo
**CPU**: 4 core - Intel Xeon E5-2630 v4 @ 2.20GHz
**RAM**: 8Gb
**Disk**: 200GB SSD

**Comment by wjdfx** [comment]
Machine Specs:
Cloud: Digitalocean
CPU: 2 core
RAM: 4Gb
Disk: 80GB SSD

**Comment by zavodil** [comment]
Machine Specs:
Cloud Hosting
CPU: 8 core
RAM: 32Gb
Disk: 240GB SSD

**Comment by xz-cn** [comment]
Machine Specs:
Cloud hosting
CPU: 8 core - Intel Xeon E5-2640 v3 @ 2.60GHz
RAM: 16Gb
Disk: 1TB

**Comment by andreisid** [comment]
Machine(s) specs:

Cloud: AWS t2.medium
CPU: 2 core
RAM: 4gb
Disk space: 50gb
Cool Benchmark:

- i ran against testnet in docker with 2 cpus, and one cpu was 100% and the other was idle. You could see in the below graph, that during peaks, the cpu did not pass over 50% usage(on a 2 cpu vm)
![image](https://user-images.githubusercontent.com/12342269/68073392-70c00700-fd98-11e9-9b1d-df6a743a3239.png)

**Comment by novy4** [comment]
Machine Specs:
Cloud Hosting
CPU: 4 core
RAM: 16Gb
Disk: 160GB SSD

**Comment by winslyn** [comment]
Machine Specs:
Cloud Hosting
CPU: 2 Core
RAM: 4 Gb
Disk: 50GB SSD

**Comment by pranaymohan** [comment]
Machine(s) specs:

GCP (n1-standard)
CPU: 2 cores
RAM: 7.5 GB
Disk space: 50 GB

**Comment by stakehost** [comment]
Machine Specs:

Physical/Co-located (shared with other chains)

CPU: 2x Xeon E5-2623 v3
64GB RAM
2TB SSD

**Comment by zhanglianghui** [comment]
Machine(s) specs:

GCP (asia-east-a)
CPU: 4 cores
RAM: 8 GB
Disk space: 200 GB

**Comment by ferat8** [comment]
Machine Specs:
Cloud Hosting
CPU: 4 core
RAM: 4 Gb
Disk: 60GB SSD

**Comment by stakery** [comment]
Machine specs:

* Cloud
* CPU: 2 cores
* RAM: 12 GB
* Disk space: 100 GB

**Comment by joesixpack** [comment]
Cloud
4 cores
4GB RAM
64GB SDD

No benchmark yet as can't get it to run.  See the open issue.

**Comment by wetezos** [comment]
Machine Specs:
Cloud Hosting
CPU: 2 Core
RAM: 2 Gb
Disk: 100GB SSD

**Comment by feibear** [comment]
**Machine Specs:**
**Cloud:** Tencent Cloud
**CPU:** 2 core
**RAM:** 4 Gb
**Bandwidth:**5 Mbps
**Disk:** 50GB SSD

**Comment by eorituz** [comment]
**Machine Specs:**
**Cloud**: DigitalOcean
**CPU**: 2 core
**RAM**: 4 GB
**Location**: Frankfurt
**Disk**: 80GB SSD

**Comment by lixa4ev2010** [comment]
Machine Specs:
QEMU VM
CPU: 2 core
RAM: 8Gb
Disk: 100GB SSD

**Comment by usnggogogo** [comment]
Machine Specs:
Cloud: aws
CPU: 2 core
RAM: 4 GB
Location: Northern Virginia
Disk: 120GB SSD
