### ISSUE TITLE
[BUG] Cannot start node

### ISSUE THREAD

**Issue by imnisen** [nearprotocol/stakewars#408]
**Describe the bug or test**
Cannot start node after it crashed.

**Specs (please complete the following information):**
 - OS ubuntu
- Which cloud / on-premise:  ucloud
- CPU:  2cores
- RAM: 8G
- Disk space:  200G

At first the code crashed of the logs as below.

[near_err_log.txt](https://github.com/nearprotocol/stakewars/files/4709407/near_err_log.txt)

So I increased the memory to 8G, then deleted data folder to resync again.

After downloading all headers,the node cannot start now, the log is as below:

[near_err_log2.txt](https://github.com/nearprotocol/stakewars/files/4709408/near_err_log2.txt)

Thanks!

**Comment by bowenwang1996** [comment]
We are fixing the trie node missing bug https://github.com/nearprotocol/nearcore/pull/2762

**Comment by jimmy3dita** [comment]
@imnisen is the bug solved now?

**Comment by imnisen** [comment]
@jimmy3dita Sure! Close now.
