### ISSUE TITLE
[BUG] Stakewars node shows in Testnet explorer

### ISSUE THREAD

**Issue by mbucci** [nearprotocol/stakewars#41]
**Describe the bug or test**
My Stakewars validator node (`stakedincweek2`) shows as a node in the [testnet explorer](https://explorer.nearprotocol.com/nodes) and not in the [tatooine explorer](https://explorer.tatooine.nearprotocol.com/nodes) as I would expect. My node's block number is consistent with the tatooine's current block, not testnet. 

**How to Reproduce**

1. No `config.json`, `genesis.json`, or `data/` in NEAR home
2. start with `scripts/start_stakewars.py --home <NEAR home>` (Docker run)
a. be a validator (not sure if this is important)
3. Wait for sync
4. Check list of Testnet and Tatooine nodes

**Expected behavior OR Outcome of test**
Tatooine explorer displays the correct set of nodes.

**Specs (please complete the following information):**
 - OS: Amazon Linux 2
- Which cloud / on-premise: Cloud (AWS EC2)
- CPU: 8
- RAM: 32GB
- Disk space: 500GB 

**Additional context**
Tatooine explorer may be displaying nodes prior to the Stakewars reset on 11/18 at 6:23p EST and Testnet is displaying nodes after that reset.

#### `nearprotocol/nearcore` Docker image digests tested:

```
sha256:2c788d4ec7b67469cc30303f1535ad700833033c42def2b3efeb2f91002271b1
sha256:4cef8d30b3713c669661cd23541ee8a19f7fda8b434e0a965cfcf7b3cdbde4ac
```

#### config.json
```json
{
  "genesis_file": "genesis.json",
  "validator_key_file": "validator_key.json",
  "node_key_file": "node_key.json",
  "rpc": {
    "addr": "0.0.0.0:3030",
    "cors_allowed_origins": [
      "*"
    ],
    "polling_config": {
      "polling_interval": {
        "secs": 0,
        "nanos": 500000000
      },
      "polling_timeout": {
        "secs": 10,
        "nanos": 0
      }
    }
  },
  "telemetry": {
    "endpoints": [
      "https://explorer.nearprotocol.com/api/nodes"
    ]
  },
  "network": {
    "addr": "0.0.0.0:24567",
    "external_address": "",
    "boot_nodes": "ed25519:6P39XGzWBCHhvGhWg2TpMFzsQtxDKz7RdkpHdW9h8Xad@34.67.252.132:24567,ed25519:HBhnKcw1vPvNdvU6uFp9DeqNVYJNMd7ZTpcEUBdxkB5T@34.74.9.7:24567,ed25519:GEWykW4RWkgaKQjc2UXawiZnXAeUShZi4Kxh4SgZihye@34.95.36.29:24567,ed25519:2W1VN16wj6ujLf6dPyHGURvrZkgJF9WMYWJT9iHKt3Wc@34.95.174.83:24567,ed25519:BzNGFkKJJF9dNyV2KeXtKC9u2n22DC7EeVerzcnsyQ2v@35.228.240.15:24567,ed25519:5RrbVojmrWvQkot2smuw2ddnUgmzgSBcxKTHUu22iY26@35.195.39.208:24567",
    "max_peers": 40,
    "handshake_timeout": {
      "secs": 20,
      "nanos": 0
    },
    "reconnect_delay": {
      "secs": 60,
      "nanos": 0
    },
    "skip_sync_wait": false,
    "ban_window": {
      "secs": 10800,
      "nanos": 0
    }
  },
  "consensus": {
    "min_num_peers": 3,
    "block_production_tracking_delay": {
      "secs": 0,
      "nanos": 100000000
    },
    "min_block_production_delay": {
      "secs": 1,
      "nanos": 0
    },
    "max_block_production_delay": {
      "secs": 2,
      "nanos": 0
    },
    "max_block_wait_delay": {
      "secs": 6,
      "nanos": 0
    },
    "reduce_wait_for_missing_block": {
      "secs": 0,
      "nanos": 100000000
    },
    "produce_empty_blocks": true
  },
  "tracked_accounts": [],
  "tracked_shards": []
}
```

**Comment by frol** [comment]
@mbucci please, take a look into `~/.near/config.json`, specifically, `telemetry` -> `endpoints` value. Do you have anything there? Do you run your node in Docker or without Docker?

**Comment by mbucci** [comment]
> @mbucci please, take a look into `~/.near/config.json`, specifically, `telemetry` -> `endpoints` value. Do you have anything there? Do you run your node in Docker or without Docker?

@frol I've updated my initial comment with my `config.json` and additional context regarding Docker. Let me know if there is additional information you would like.

**Comment by frol** [comment]
@mbucci that is odd, the endpoint should be `"https://explorer.tatooine.nearprotocol.com/api/nodes"`. Do you have any guess why your config has `"https://explorer.nearprotocol.com/api/nodes"`? I guess it might be some bug in the initialization on nearcore end, but let me know if you have followed some sort of instructions to put it there by hand.

**Comment by mbucci** [comment]
> @mbucci that is odd, the endpoint should be `"https://explorer.tatooine.nearprotocol.com/api/nodes"`. Do you have any guess why your config has `"https://explorer.nearprotocol.com/api/nodes"`? I guess it might be some bug in the initialization on nearcore end, but let me know if you have followed some sort of instructions to put it there by hand.

@frol I haven't done anything by hand. I've only ever run the `start_stakewars.py` script.

**Comment by frol** [comment]
@mbucci Thank you for letting me know. I will dig into the problem and let you know once I have something.

**Comment by mbucci** [comment]
thank you @frol

**Comment by frol** [comment]
FYI, I have pined down the root cause for the issue and reported it here: https://github.com/nearprotocol/nearcore/issues/1788
