### ISSUE TITLE
[BUG]cargo path missing in nodelib.py

### ISSUE THREAD

**Issue by hoekevin** [nearprotocol/stakewars#44]
line 50 of nodelib.py:
`[os.path.expanduser('cargo'), 'build'] + flags)`
should be changed to:
`[os.path.expanduser('~/.cargo/bin/cargo'), 'build']  + flags)`

when running the following command  by sudo, a normal privilege user's PATH  does not be passed to root,so a  absoult PATH must be specified before 'cargo'

`sudo ./scripts/start_stakewars.py --init --signer-keys --account-id=<your_account_id> --nodocker`

otherwise, an error of "no such file" will occure.

**Comment by ailisp** [comment]
Not a bug. Start from Nov 20 no longer need sudo to run both docker and native version. And this script is also used in ci, which cargo has a different path. If want to use sudo, pass env so sudo can still find your cargo: `sudo env "PATH=$PATH" scripts/...`
