### ISSUE TITLE
[BUG] docker error at running genesis-csv-to-json

### ISSUE THREAD

**Issue by marco-sundsk** [nearprotocol/stakewars#45]
**Describe the bug or test**
When exec start_stakewars.py, it shows error:  
error:  Found argument '--tracked-shards' which wasn't expected, or isn't valid in this context  
  
Here is the detail info 
root@buildlinks-test-platform:~/near_stakewars/nearcore# docker logs -f 383714fe3e5d
Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
Running /etc/my_init.d/10_syslog-ng.init...
Nov 20 13:22:04 383714fe3e5d syslog-ng[13]: syslog-ng starting up; version='3.13.2'
Booting runit daemon...
Runit started as PID 21
Running genesis-csv-to-json --home=/srv/genesis-csv-to-json --chain-id=stakewars --tracked-shards=...
error: Found argument '--tracked-shards' which wasn't expected, or isn't valid in this context
USAGE:
    genesis-csv-to-json --chain-id <chain-id> --home <home>
For more information try --help
genesis-csv-to-json exited with status 1.
Shutting down runit daemon (PID 21)...

**How to Reproduce**
1. clean .near
2. ./scripts/start_stakewars.py --init --signer-keys --account-id=<your_account_id>
3. downlaod and move accounts.csv into  ~/.near folder
4. Run scripts/start_stakewars.py

**Expected behavior OR Outcome of test**
start node successfully.

**Specs (please complete the following information):**
 - OS: Ubuntu 18.04
- Which cloud / on-premise:  AliYun
- CPU: Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
- RAM: 4G
- Disk space: 500G SSD

**Additional context**
docker image info is here:
root@buildlinks-test-platform:~/near_stakewars/nearcore/scripts# docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
nearprotocol/nearcore   stakewars           040fdad633e6        42 hours ago        234MB
nearprotocol/nearcore   latest              4b24bba194ad        2 days ago          234MB
v2tec/watchtower        latest              3069a9fb302a        20 months ago       9.49MB

**Screenshots Optional**
![bug1](https://user-images.githubusercontent.com/47070476/69244861-c130c480-0be0-11ea-8f78-ffcbc65df553.png)

**Comment by ailisp** [comment]
@bowenwang1996 Do you aware of this old version and the fix? The stakewar tag is override by newer one, and in the newer stakewars this issue is fixed, as in:
```
nearprotocol/nearcore         stakewars           f805b2a1ae69        21 hours ago        128MB
```

**Comment by bowenwang1996** [comment]
Yes it is probably incompatible docker images.
