### ISSUE TITLE
[BUG] Latest Staging Fails on Compiling Near Client

### ISSUE THREAD

**Issue by joesixpack** [nearprotocol/stakewars#47]
**Describe the bug or test**
Checked out the latest staging branch and then:

j@j-desktop:~/nearcore$ ./scripts/start_stakewars.py --nodocker
****************************************************
* Running NEAR validator node for Stake Wars *
****************************************************
cargo 1.40.0-nightly (8b0561d68 2019-09-30)
   Compiling near-client v0.1.0 (/home/j/nearcore/chain/client)
error: expected one of `.`, `;`, `?`, `}`, or an operator, found `=>`
    --> chain/client/src/client.rs:1122:62
     |
1122 |                 Err(RuntimeError::UnexpectedIntegerOverflow) => {
     |                                                              ^^ expected one of `.`, `;`, `?`, `}`, or an operator here

error[E0308]: mismatched types
    --> chain/client/src/client.rs:1118:21
     |
1110 | /                 if active_validator {
1111 | |                     debug!(
1112 | |                         target: "client",
1113 | |                         "Recording a transaction. I'm {:?}, {}",
...    |
1118 | |                     NetworkClientResponses::ValidTx
     | |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected (), found enum `near_network::types::NetworkClientResponses`
1119 | |                 } else {
1120 | |                     self.forward_tx(tx)
1121 | |                 }
     | |                 -- help: consider using a semicolon here
     | |_________________|
     |                   expected this to be `()`
     |
     = note: expected type `()`
                found type `near_network::types::NetworkClientResponses`

error[E0308]: mismatched types
    --> chain/client/src/client.rs:1120:21
     |
1110 | /                 if active_validator {
1111 | |                     debug!(
1112 | |                         target: "client",
1113 | |                         "Recording a transaction. I'm {:?}, {}",
...    |
1120 | |                     self.forward_tx(tx)
     | |                     ^^^^^^^^^^^^^^^^^^^ expected (), found enum `near_network::types::NetworkClientResponses`
1121 | |                 }
     | |_________________- expected this to be `()`
     |
     = note: expected type `()`
                found type `near_network::types::NetworkClientResponses`
help: try adding a semicolon
     |
1120 |                     self.forward_tx(tx);
     |                                        ^
help: consider using a semicolon here
     |
1121 |                 };
     |                  ^

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `near-client`.

To learn more, run the command again with --verbose.
Compilation failed, aborting
j@j-desktop:~/nearcore$

**Comment by bowenwang1996** [comment]
Which commit are you on? Are you sure it is latest?

**Comment by joesixpack** [comment]
I'm closing this because a clean pull then switching to staging seems to have fix it.  Probably not best to switch branches without an update first.
