### ISSUE TITLE
[Choose one --> BUG | TEST] ...

### ISSUE THREAD

**Issue by maxcript** [nearprotocol/stakewars#489]
**Describe the bug or test**
When in bot I choose option /viewaccount and type username andrew_builder it show nothing, it is weird thing. But when you choose andrew_builder.betanet it works in right way. If you think that andrew_builder doesn't exist please use explorer and see that it exist.

**How to Reproduce**
1. Go to '/viewaccount'
2. Type 'andrew_builder'
4. See thing

**Expected behavior OR Outcome of test**
If it works in right way you will see info about user, but now it isn't

**Screenshots Optional**
https://prnt.sc/t0og8k
https://prnt.sc/t0ohzn

**Comment by zavodil** [comment]
Probably it's a visual bug with underscore character for telegram markdown parse mode. Try now please.
And please create next issues in the repo https://github.com/zavodil/nearup_telegram_bot
