### ISSUE TITLE
[BUG] How to restore the stake pool account of near-shell timeout error

### ISSUE THREAD

**Issue by marshall-d-teach** [nearprotocol/stakewars#525]
I create the stake pool account with `near create_account pool.xiaoshen.betanet --masterAccount=xiaoshen.betanet --initialBalance 30`, then the output says rpc timeout and no account file created in `~/.near-credentials/betanet/`.
However I find that the stakepool account already created and the master account balance is cut off.  So I wonder how to handle this problem?  It seems the near-shell doesn't handle this error well. How to recreate the stake pool credentials file?

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/52067333/85992195-19f1f680-ba27-11ea-9a77-fedd04490b40.png">

**Comment by bowenwang1996** [comment]
> It seems the near-shell doesn't handle this error well.

Yes we are working on it. https://github.com/near/near-api-js/issues/344
