### ISSUE TITLE
[BUG] Valid proposals doesn't turn into validator seat

### ISSUE THREAD

**Issue by eorituz** [nearprotocol/stakewars#536]
**Describe the bug or test**
My stakepool `stakeing.arno_nym.betanet` submits valid proposals with enough near staked but isn't becoming a validator.
Since two days now, I permanently bid 163k
```
oliver@bbpc:~$ near proposals | grep arno
| Proposal(Accepted) | stakeing.arno_nym.betanet      | 163,423            | 1       |
```
The current seatprice is 112k
```
oliver@bbpc:~$ near validators current
Using options: {
  networkId: 'betanet',
  nodeUrl: 'https://rpc.betanet.near.org',
  contractName: undefined,
  walletUrl: 'https://wallet.betanet.near.org',
  helperUrl: 'https://helper.betanet.near.org',
  helperAccount: 'betanet',
  useLedgerKey: "44'/397'/0'/0'/1'",
  epoch: 'current',
  initialBalance: null
}
Validators (total: 97, seat price: 112,286):
```

**How to Reproduce**
Hard to say as I do not have enough NEAR to reproduce it myself. Might very well be that I fucked up in the setup....

**Expected behavior OR Outcome of test**
Become a validator after successfully bidding enough in auction

**Additional context**
~~The only thing that might have gone wrong could be me adding a wrong public key in the init of my staking contract.
```
near call stakingPool_ID new '{"owner_id": "account_ID", "stake_public_key": "CE3QAXyVLeScmY9YeEyR3Tw9yXfjBPzFLzroTranYtVb", "reward_fee_fraction": {"numerator": 10, "denominator": 100}}' --account_id stakingPool_ID
```
~~

Edit: The owner of the pool is set correctly.
```
oliver@bbpc:~$ near view stakeing.arno_nym.betanet get_owner_id '{}'
Using options: {
  networkId: 'betanet',
  nodeUrl: 'https://rpc.betanet.near.org',
  contractName: 'stakeing.arno_nym.betanet',
  walletUrl: 'https://wallet.betanet.near.org',
  helperUrl: 'https://helper.betanet.near.org',
  helperAccount: 'betanet',
  useLedgerKey: "44'/397'/0'/0'/1'",
  methodName: 'get_owner_id',
  args: '{}',
  initialBalance: null
}
View call: stakeing.arno_nym.betanet.get_owner_id({})
'arno_nym.betanet'
```

@jimmy3dita ~~what happens if I submit a wrong public key here? And would you mind adding an extra sentence explaining if the stake_public_key is the public key of the stake pool Id or the public key of the owner? (I don't remember which one I took...)~~
It would be great if you could add an extra sentence in the [challenge001](https://github.com/nearprotocol/stakewars/blob/master/challenges/challenge001.md) stating that the `stake_public_key` the public key of owner.

**Comment by narniec** [comment]
Perhaps there is a solution to your problem. Have you watched this?
https://github.com/nearprotocol/stakewars/blob/master/troubleshooting.md

**Comment by eorituz** [comment]
@narniec Thank you but that's unfortunately not it...
I'm using my warchest bot to stake and it calls 
`near call {stake_pool_id} stake \'{{"amount": "{amount_to_stake}"}}\' --accountId {accound_id}`

And I also set the right owner:
```
oliver@bbpc:~$ near view stakeing.arno_nym.betanet get_owner_id '{}'
Using options: {
  networkId: 'betanet',
  nodeUrl: 'https://rpc.betanet.near.org',
  contractName: 'stakeing.arno_nym.betanet',
  walletUrl: 'https://wallet.betanet.near.org',
  helperUrl: 'https://helper.betanet.near.org',
  helperAccount: 'betanet',
  useLedgerKey: "44'/397'/0'/0'/1'",
  methodName: 'get_owner_id',
  args: '{}',
  initialBalance: null
}
View call: stakeing.arno_nym.betanet.get_owner_id({})
'arno_nym.betanet'
```

**Comment by bowenwang1996** [comment]
It is possible that your validator setup is wrong and therefore your node didn't produce enough blocks. Did you monitor that?

**Comment by eorituz** [comment]
Ok It looks like I messed something up in my validator setup which leads to me getting kicked out every time I got a seat.
Thank you bowen.
