### ISSUE TITLE
I met thread panicked while panicking. aborting. Illegal instruction (core dumped) when I use command rustup update stable

### ISSUE THREAD

**Issue by youlaiwuqu** [nearprotocol/stakewars#537]
After installation of rustup, I use command **rustup target add wasm32-unknown-unknown** but receive **error: no default toolchain configured**.
Then I use command **rustup update stable** or **rustup default stable** but receive **thread panicked while panicking. aborting.
Illegal instruction (core dumped)** as below picture. What should I do to solve this? My system is Ubuntu under windows.
https://i.ibb.co/svt39Hy/1.png

**Comment by youlaiwuqu** [comment]
My email address is ljjathena@163.com

**Comment by jimmy3dita** [comment]
This type of issue can be solved by looking at Rust documentation
