### ISSUE TITLE
[TEST] near send not working

### ISSUE THREAD

**Issue by sweetpotatoz** [nearprotocol/stakewars#60]
**Describe the bug or test**

got below errors, when try to do near send with near-shell

_Error:  { Error: send_tx_commit has timed out
    at JsonRpcProvider.sendJsonRpc (/usr/lib/node_modules/near-shell/node_modules/nearlib/lib/providers/json-rpc-provider.js:60:23)
    at process._tickCallback (internal/process/next_tick.js:68:7) type: 'TimeoutError' }_

account id are valid on the tatooine network
jleonyw4 is created with wallet GUI, with enough balance to send
vow4 is in genesis

**How to Reproduce**
near state jleonyw4
{ networkId: 'tatooine',
  nodeUrl: 'https://rpc.tatooine.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.tatooine.nearprotocol.com' }
Account jleonyw4
{ amount: '10000000000000000000',
  code_hash: '11111111111111111111111111111111',
  locked: '0',
  storage_paid_at: 742,
  storage_usage: 346 }

near state vow4
{ networkId: 'tatooine',
  nodeUrl: 'https://rpc.tatooine.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.tatooine.nearprotocol.com' }
Missing public key for vow4 in tatooine
Account vow4
{ amount: '10000000000000000000',
  code_hash: '11111111111111111111111111111111',
  locked: '10032145920893081018',
  storage_paid_at: 0,
  storage_usage: 182 }

near send jleonw4 vow4 1000000000000000000
{ networkId: 'tatooine',
  nodeUrl: 'https://rpc.tatooine.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.tatooine.nearprotocol.com' }
Sending 1000000000000000000 NEAR to vow4 from jleonw4
Error:  { Error: send_tx_commit has timed out
    at JsonRpcProvider.sendJsonRpc (/usr/lib/node_modules/near-shell/node_modules/nearlib/lib/providers/json-rpc-provider.js:60:23)
    at process._tickCallback (internal/process/next_tick.js:68:7) type: 'TimeoutError' }

**Expected behavior OR Outcome of test**
1 NEAR should be sent from jleonyw4 to vow4

**Specs (please complete the following information):**
 - OS:
- Which cloud / on-premise: 
- CPU: 
- RAM: 
- Disk space: 

**Additional context**

**Screenshots Optional**

**Comment by bowenwang1996** [comment]
Can you reproduce the same error if you try again? I think it might be that I misconfigured something in the beginning.

**Comment by sweetpotatoz** [comment]
> Can you reproduce the same error if you try again? I think it might be that I misconfigured something in the beginning.

try near login, but it is failing now.

**Comment by bowenwang1996** [comment]
what is the error?

**Comment by sweetpotatoz** [comment]
i created a new account id jleonyw4b in https://wallet.tatooine.nearprotocol.com/
still get the same error when i try 

near send jleonw4b vow4 1000000000000000000

{ networkId: 'tatooine',
  nodeUrl: 'https://rpc.tatooine.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.tatooine.nearprotocol.com' }
Sending 1000000000000000000 NEAR to vow4 from jleonw4b
Error:  { Error: send_tx_commit has timed out
    at JsonRpcProvider.sendJsonRpc (/usr/lib/node_modules/near-shell/node_modules/nearlib/lib/providers/json-rpc-provider.js:60:23)
    at process._tickCallback (internal/process/next_tick.js:68:7) type: 'TimeoutError' }

**Comment by bowenwang1996** [comment]
That's strange. It seems that `jleonw4b` doesn't exist. Are you sure that you've created this account?

**Comment by sweetpotatoz** [comment]
https://explorer.tatooine.nearprotocol.com/accounts/jleonyw4b
https://explorer.tatooine.nearprotocol.com/accounts/jleonyw4
both can be view in explorer (tatooine)
i created both after the call, so the network was already started for a while by then.  the explorer was already up and working before I created these accounts.

**Comment by sweetpotatoz** [comment]
i can do near send now, after near login.  not sure what was the issue earlier

**Comment by bowenwang1996** [comment]
@sweetpotatoz did you still use `jleonw4b`? It looks like the account doesn't exist

**Comment by sweetpotatoz** [comment]
> @sweetpotatoz did you still use `jleonw4b`? It looks like the account doesn't exist

https://explorer.tatooine.nearprotocol.com/accounts/jleonyw4b
yeah i was still using it 2 days ago
when i run near state jleonyw4b now, i can still query the account state

near state jleonyw4b
[WARNING] Didn't find config at /home/<userid>/src/config, using default shell config
{ networkId: 'tatooine',
  nodeUrl: 'https://rpc.tatooine.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.tatooine.nearprotocol.com' }
Account jleonyw4b
{ amount: '8100000000000000000',
  code_hash: '11111111111111111111111111111111',
  locked: '0',
  storage_paid_at: 23403,
  storage_usage: 346 }
