### ISSUE TITLE
[BUG] Error on receival of header: DB Not Found Error

### ISSUE THREAD

**Issue by imnisen** [nearprotocol/stakewars#61]
**Describe the bug or test**
The log of nearcore outputs like below a lot:

```
[2019-11-28T03:03:33Z ERROR near_client::client_actor] Error on receival of header: DB Not Found Error: 6jqcMy3CYz8HGRe111oR5biA3BnCsmuadHVbJjRPLAUp
     Cause: Unknown
     Backtrace:
```

**How to Reproduce**
It didn't appear for last weeks, but show an error of this week's testnet.
1. Follow the doc [To get the local node started](https://github.com/nearprotocol/stakewars#how-to-stake-with-a-wallet-generated-account)
2. After downloading all headers, this error message will output

**Expected behavior OR Outcome of test**
It should not output the `Cause: Unknow` or `Backtrace:` things.

**Specs (please complete the following information):**
 - OS: Ubuntu 16.04.3 LTS
- Which cloud / on-premise:  Ucloud
- CPU: 2core
- RAM: 4G
- Disk space:  200G SSD

**Screenshots Optional**
![image](https://user-images.githubusercontent.com/12237169/69774149-11ef8100-11d0-11ea-8dce-db1920fe6cba.png)

![image](https://user-images.githubusercontent.com/12237169/69774281-714d9100-11d0-11ea-8b61-25984647962c.png)

**Comment by bowenwang1996** [comment]
Should be fixed now
