### ISSUE TITLE
[BUG] Validator not anymore after running for a while

### ISSUE THREAD

**Issue by marshall-d-teach** [nearprotocol/stakewars#62]
**Describe the bug or test**
I have successfully become a validator. However, after running for about 1 hours, I am not a validator any more

**How to Reproduce**
1. Follow the steps in the doc become a validator
2. Run for a while
3. Not a validator!

**Expected behavior OR Outcome of test**
I should be a validator always if I interrupt

**Specs (please complete the following information):**
 - OS: ubuntu 16.04
- Which cloud / on-premise: GCP
- CPU:  2core
- RAM:  4G
- Disk space:  100G SSD

**Screenshots Optional**
![image](https://user-images.githubusercontent.com/52067333/69775656-5a10a280-11d4-11ea-82b2-c52b809bdf0f.png)

**Comment by frol** [comment]
A related issue: #63
