### ISSUE TITLE
[TEST] Require an elegant way to let genesis validator to restake after kicked off for some reason

### ISSUE THREAD

**Issue by marco-sundsk** [nearprotocol/stakewars#63]
**Describe the bug or test**
Say node Alice is a validator in genesis file. When she is kicked off from validator set for some reason, What shall she do to rejoin the validator set? Cause, the normal way of staking is to using near-shell tool with near stake xxx followed by near login. But, as a genesis validator, her signer key (let's call signer accountid Alice_Signer ) is not generated through online wallet. Generally, Alice_Signer is generated through --signer_keys option in python script and there is only a json key file with accountid, public key and secret key. Alice can NOT import her Alice_Signer to online wallet for no Mnemonic phrase for the account in Alice hand. 

So, near login are invalid in this scenario. Altough, she can add keyPath and masterAccount params to the near-shell tool, it is not good that NOT able to opeation account Alice_Signer through online wallet.

My suggestion is, either add Mnemonic words in python script tools or let online wallet can import secret key directly.

**How to Reproduce**
1. Be a genesis validator
2. Start your node at a poor network env to let it be kicked from validator set by protocol
3. Then, find a way to rejoin validator set.
4. You will find it is not very convenient.

**Expected behavior OR Outcome of test**
I hope there would be an elegant way to let genesis validators can oprate their accounts through online wallet.

**Specs (please complete the following information):**
 - OS: Ubuntu 18.04
- Which cloud / on-premise:  AliYun
- CPU: Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
- RAM: 4G
- Disk space: 500G SSD

**Additional context**
near-shell version: 0.14.2

**Screenshots Optional**
N/A

**Comment by frol** [comment]
A related issue: #62

**Comment by bowenwang1996** [comment]
I created an issue in near-shell for this https://github.com/nearprotocol/near-shell/issues/208
