### ISSUE TITLE
[ BUG | TEST] Tatooine will report username already exists after account creation

### ISSUE THREAD

**Issue by caesarchad** [nearprotocol/stakewars#65]
**Describe the bug or test**
On testnet wallet https://wallet.tatooine.nearprotocol.com/create, user cannot create new account for sometimes.
![image](https://user-images.githubusercontent.com/17776934/69796272-8e5b7300-1182-11ea-91d3-42f2dd151500.png)

**Comment by frol** [comment]
It is a known issue of misreporting of issues with the blockchain network.

@vgrichina Do we have a tracking issue for a proper errors handling?

**Comment by bowenwang1996** [comment]
I created an issue in wallet https://github.com/nearprotocol/near-wallet/issues/258

**Comment by joesixpack** [comment]
Still occurring. Can't login for stakewars staking because of the username taken already bug. I'm wondering exactly where the seed phrase is provided also (not that it finds the username in that section).

**Comment by vgrichina** [comment]
@frol Created tracking issue here https://github.com/nearprotocol/near-wallet/issues/289

**Comment by vgrichina** [comment]
@bowenwang1996 what would be good time limit for account creation?

**Comment by bowenwang1996** [comment]
Even when network is slow 20s should definitely be enough

**Comment by joesixpack** [comment]
![image](https://user-images.githubusercontent.com/23145642/71251587-9d43ca00-22d7-11ea-8a6c-fc7103e828ee.png)

**Comment by joesixpack** [comment]
![image](https://user-images.githubusercontent.com/23145642/71251653-cfedc280-22d7-11ea-88e0-71c6208fa79f.png)
