### ISSUE TITLE
[TEST] accounts.csv in master branch committed 4 hrs ago having genesis time of Nov 26

### ISSUE THREAD

**Issue by sweetpotatoz** [nearprotocol/stakewars#66]
**Describe the bug or test**
accounts.csv in master branch committed 4 hrs ago having genesis time of Nov 26

**How to Reproduce**
4. See thing

**Expected behavior OR Outcome of test**

**Specs (please complete the following information):**
 - OS:
- Which cloud / on-premise: 
- CPU: 
- RAM: 
- Disk space: 

**Additional context**

**Screenshots Optional**

**Comment by bowenwang1996** [comment]
Not an issue. We will reset it when it is close to the call.
