### ISSUE TITLE
[Choose one --> BUG] wallet GUI still shows account from previous stakewars network

### ISSUE THREAD

**Issue by sweetpotatoz** [nearprotocol/stakewars#71]
**Describe the bug or test**
Attached screen capture.
![near_wallet](https://user-images.githubusercontent.com/1692346/70031343-fc21f780-15e5-11ea-9911-bdcae854f399.png)

as shown in the screen capture, only vow5 was created in current network.
the rest of the accounts still showing in the account dropdown box for user to switch to
likes
validators_online, jleonyw4, jleonyw4b, jleony

**How to Reproduce**
4. See thing

**Expected behavior OR Outcome of test**

**Specs (please complete the following information):**
 - OS:
- Which cloud / on-premise: 
- CPU: 
- RAM: 
- Disk space: 

**Additional context**

**Screenshots Optional**

**Comment by vgrichina** [comment]
Workaround is to clear local storage on network upgrade:

https://mage2.pro/t/topic/1659

**Comment by vgrichina** [comment]
@bowenwang1996 do I understand correctly that we won't be resetting state like this anymore?

**Comment by bowenwang1996** [comment]
Yeah that is the plan
