### ISSUE TITLE
[BUG] tatooine explorer crash again

### ISSUE THREAD

**Issue by imnisen** [nearprotocol/stakewars#72]
**Describe the bug or test**
https://explorer.tatooine.nearprotocol.com/ crash again. 
Last block is 7hr ago

**Expected behavior OR Outcome of test**
The newest block is 47358.

**Additional context**
It fails a lot of times.

**Screenshots Optional**
![image](https://user-images.githubusercontent.com/12237169/70032342-3f7d6580-15e8-11ea-89c1-7554a8eb94ec.png)

**Comment by frol** [comment]
Resolved with https://github.com/nearprotocol/near-explorer/pull/135
