### ISSUE TITLE
[TEST] Log message for block produced and missed

### ISSUE THREAD

**Issue by swswsw** [nearprotocol/stakewars#79]
**Describe the bug or test**
Number of blocks missed is important info before we are kicked out as validator.  

**How to Reproduce**
1. create a validator node

**Expected behavior OR Outcome of test**
Log message showing that number of blocks produced and how many are missed.

**Specs (please complete the following information):**
 - OS: ubuntu 18.04
- Which cloud / on-premise: AWS 
- CPU: not relevant for this issue
- RAM: not relevant for this issue
- Disk space: not relevant for this issue

**Comment by nearmax** [comment]
Chain should log that assigned to @SkidanovAlex
