### ISSUE TITLE
[BUG] Staked amount remains locked after getting slashed

### ISSUE THREAD

**Issue by krisboit** [nearprotocol/stakewars#86]
**Describe the bug or test**
After i was slashed the staked amount remained locked, even 2 hours after.

**How to Reproduce**
1. Start a validator
2. Get slashed by doing double sign

**Expected behavior OR Outcome of test**
I would expect that after 3 epochs the staked amount to be unlocked.

**Specs (please complete the following information):**
 - OS: Ubuntu 18.04
- Which cloud : Hetzner 
- CPU: 2vCPU
- RAM: 4Gb
- Disk space: 40Gb 

**Additional context**
check account state 2 hours after i got slashed
```
$ NODE_ENV=tatooine near state moonlet1
[WARNING] Didn't find config at /Users/krisboit/Work/projects/validator/automation/src/config, using default shell config
{ networkId: 'tatooine',
  nodeUrl: 'https://rpc.tatooine.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.tatooine.nearprotocol.com' }
Account moonlet1
{ amount: '9999899999999988000',
  block_height: 27480,
  code_hash: '11111111111111111111111111111111',
  locked: '7283814223271591051',
  storage_paid_at: 17880,
  storage_usage: 346,
  formattedAmount: '9.999899999999988' }
```

**Comment by potatodepaulo** [comment]
Points assigned.
@bowenwang1996 Is this still an issue
