### ISSUE TITLE
[Feature Request] Enforce Node >= 10 for near-shell

### ISSUE THREAD

**Issue by eorituz** [nearprotocol/stakewars#90]
I had somewhat of a confusing time figuring out why some things didn't work for me until I found a tiny 
```
WARN engine near-shell@0.16.0: wanted: {"node":">= 10"} (current: {"node":"8.10.0","npm":"3.5.2"})
```
message in the beginning of the near shell installation. 

To be fair it's not too hard to come up with the idea of updating node but the installation still succeeds.

However, enforcing node>=10 would improve the UX for some user installing npm&node from Ubuntu PPA by a lot.

**Comment by frol** [comment]
It was discussed here: https://github.com/nearprotocol/near-shell/issues/186

I also agree, that we should strictly forbid the old version of node to avoid these cryptic errors.
