### ISSUE TITLE
[BUG] Wallet account create not working properly when opened in multiple tabs

### ISSUE THREAD

**Issue by krisboit** [nearprotocol/stakewars#94]
**Describe the bug or test**
When wallet is opened in multiple tabs, account creation is not working properly. Last change wins when writing in local storage.

**How to Reproduce**
1. Go to https://wallet.tatooine.nearprotocol.com/
2. Make sure you have one account created
3. Open another tab with https://wallet.tatooine.nearprotocol.com/
4. on 1st tab create a new account (acc1)
5. on 2nd tab create a new account (acc2)
6. observe available accounts, only acc2 is in the list, acc1 was overwritten

**Expected behavior OR Outcome of test**
Even if wallet is opened in more than one tab, it should work properly.

**Comment by potatodepaulo** [comment]
@vgrichina @kcole16 this looks like it may still be an issue.
