### ISSUE TITLE
[BUG] Explorer has a memory leak when kept in a tab for long time

### ISSUE THREAD

**Issue by krisboit** [nearprotocol/stakewars#96]
**Describe the bug or test**
Explorer (https://explorer.tatooine.nearprotocol.com/) is using a lot of resources (memory and CPU) if it's kept in a tab for some time (in my case after 1-2 hours)

**How to Reproduce**
1. Go to https://explorer.tatooine.nearprotocol.com/
2. Leave the website open
3. After a while you can notice high CPU usage (at least 30% constantly)

**Specs (please complete the following information):**
 - OS: macos
- Which cloud / on-premise:  personal laptop
- CPU: 3,1 GHz Intel Core i7 (dual core)
- RAM: 16Gb
- Disk space: 512 Gb

**Screenshots Optional**
![Screenshot 2019-12-18 at 11 12 07](https://user-images.githubusercontent.com/9469296/71072869-01f00f00-2188-11ea-9264-6dbcb6b8417f.png)

**Comment by frol** [comment]
Yeah, it is a known problem: https://github.com/nearprotocol/near-explorer/issues/144. We are on top of it.
