### ISSUE TITLE
[TEST] Try to stake more tokens than my account has funds

### ISSUE THREAD

**Issue by eorituz** [nearprotocol/stakewars#97]
**Describe the bug or test**
I tried to stake with more tokens than I actually had `near stake arno_nym_5 ed25519:H8Mpsr5ziMYztMTzG3DDDcdGtUGSVo4M4nzkjS5JLjSN 100000000000000000000000000000000`
Which of course fails as expected 
```
root@arnonym5:~/staking# near stake arno_nym_5 ed25519:H8Mpsr5ziMYztMTzG3DDDcdGtUGSVo4M4nzkjS5JLjSN 100000000000000000000000000000000
[WARNING] Didn't find config at /root/staking/src/config, using default shell config
{
  networkId: 'default',
  nodeUrl: 'https://rpc.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.nearprotocol.com'
}
Staking 100000000000000000000000000000000 (100000000000000000000000000000000) on arno_nym_5 with public key = ed25519:H8Mpsr5ziMYztMTzG3DDDcdGtUGSVo4M4nzkjS5JLjSN.
Error:  TypedError: Transaction GQNrjXp8YG4hQgHyzC4EqayqfYPcVGP7wd1oEcCCxd7D failed. Account "arno_nym_5" tries to stake 100000000000000000000000000000000, but has staked 10000000000999956231 and only has 998999902040
    at Account.signAndSendTransaction (/usr/lib/node_modules/near-shell/node_modules/nearlib/lib/account.js:88:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async exports.stake (/usr/lib/node_modules/near-shell/index.js:156:20)
    at async Object.handler (/usr/lib/node_modules/near-shell/utils/exit-on-error.js:4:9) {
  type: 'ActionError::TriesToStake'
}
```

However, my wallet summary shows me the transaction as it would have succeeded
![image](https://user-images.githubusercontent.com/3756671/71095286-9cfae000-21ac-11ea-8165-5820d07d2cd6.png)
The only way to figure out if the tx succeeded is to look up the transaction hash in the explorer/ via near shell.
 

**How to Reproduce**
1. Try to stake with more tokens than your account has funds `near stake [accountId] [stakingKey] 100000000000000000000000000000000,`
2. Check the summary section of your wallet at https://wallet.nearprotocol.com/

**Expected behavior OR Outcome of test**
I'd expect the transaction to be marked as "failed" or "unsuccessful" as I might not remember when I check my summary in a couple of days/weeks/months.

I'd love to have some "standard highlighting" like etherscan does with failed transactions.

Right now I only get a `Result not found!`
![image](https://user-images.githubusercontent.com/3756671/71095744-6a9db280-21ad-11ea-9dfe-0c397aac2f66.png)
However, after some minutes I was able to look up the Tx in the explorer. So you might want to consider showing "unconfirmed Tx" in the explorer as well or add something like "It takes a couple of minutes for transactions to show up in the explorer" to the error message

**Remark**
Failing `near send <sender> <receiver> <amount>` transactions do not show up at all. Are they not part of the state? If they are part of the state they should also show up in the wallet summary.

**Comment by frol** [comment]
This issue is touching several items:

* Wallet does not show a transaction status /cc @vgrichina (this is due to the missing information from nearcore API: https://github.com/nearprotocol/nearcore/issues/1880)
* Explorer search should work for recent transactions: https://github.com/nearprotocol/near-explorer/issues/153
* @vgrichina Should near-shell check for the currently available amount before sending staking and transfer transactions?

**Comment by bowenwang1996** [comment]
I don't think near-shell should check currently available amount before sending transactions because there might be transactions going on simultaneously that will change the balance of the account.

**Comment by potatodepaulo** [comment]
Issues tracked elsewhere. Points assigned.
