### ISSUE TITLE
[TEST + BUG] Running multiple docker container on one host (different communication ports)

### ISSUE THREAD

**Issue by eorituz** [nearprotocol/stakewars#98]
**Describe the bug or test**
I wanted to run more than just one node on a single machine.

_<del>
I tried to change the port mapping between docker and the host by hardcoding the port mapping in [nearlib here](https://github.com/nearprotocol/nearcore/blob/master/scripts/nodelib.py#L146).
This was necessary because changing the network_port in config.json only leads to docker trying to map a wrong port. (Because of the implementation of [`get_port`](https://github.com/nearprotocol/nearcore/blob/master/scripts/nodelib.py#L128))
However, Docker still tries to bind `0.0.0.0:24567` when I run the start_stakewars script.
```
root@arnonym6:~/fork_nearcore# scripts/start_stakewars.py --home=/root/.near_forked/
****************************************************
* Running NEAR validator node for Stake Wars *
****************************************************
Genesis already exists
Starting NEAR client and Watchtower dockers...
docker: Error response from daemon: driver failed programming external connectivity on endpoint nearcore_diff_ports (4d6ce32ea7e0a69c34c7796483b29d7839c9c74b17a739eccf19861d1e5daaac): Bind for 0.0.0.0:24567 failed: port is already allocated.
Traceback (most recent call last):
  File "scripts/start_stakewars.py", line 38, in <module>
    start_stakewars(args.home, not args.debug, nodocker, args.image, telemetry_url=TELEMETRY_URL, verbose=args.verbose, tracked_shards=args.tracked_shards)
  File "/root/fork_nearcore/scripts/nodelib.py", line 306, in start_stakewars
    run_docker(image, home, boot_nodes='', telemetry_url=telemetry_url, verbose=verbose)
  File "/root/fork_nearcore/scripts/nodelib.py", line 150, in run_docker
    envs + [image])
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['docker', 'run', '-u', '0:0', '-d', '-p', u'3030:5001', '-p', u'24567:24568', '-v', '/root/.near_forked/:/srv/near', '-v', '/tmp:/tmp', '--ulimit', 'core=-1', '--name', 'nearcore_diff_ports', '--restart', 'unless-stopped', '-e', 'BOOT_NODES=', '-e', 'TELEMETRY_URL=https://explorer.tatooine.nearprotocol.com/api/nodes', 'nearprotocol/nearcore:stakewars']' returned non-zero exit status 125
```
</del>_

**Edit: This was not necessary as changing the Ports in `~/.near/config.json` is according to @frol enough to change the ports.**

**Expected behavior OR Outcome of test**
<del>I'd like to have an easier way to change the ports. (Since I badly failed)
I either want to run multiple nodes on the same droplet or maybe Port 24567 is already occupied for whatever reason
</del>

**Additional comments**
Also, I'd love to have some more documentation on the config.json file (searched the docs for it but didn't find anything). Since that should be the go-to point for changing settings, right?

**Edit:**
<del>
I also tried to change the ports in the code and expose the corresponding ports in the [Dockerfile](https://github.com/nearprotocol/nearcore/blob/master/Dockerfile#L48). 
Disclaimer: I'm not a docker expert.
Anyway I was not able to build the Docker container, I'm not sure if your Dockerfile is corrupt or if you used a specific build environment.
```
root@arnonym6:~/fork_nearcore# DOCKER_BUILDKIT=1 docker build -t nearcore-dev -f Dockerfile .
[+] Building 0.1s (3/3) FINISHED                                                                                                                                                
 => [internal] load build definition from Dockerfile                                                                                                                       0.0s
 => => transferring dockerfile: 32B                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                          0.0s
 => => transferring context: 35B                                                                                                                                           0.0s
 => ERROR resolve image config for docker.io/docker/dockerfile-upstream:experimental                                                                                       0.1s
------
 > resolve image config for docker.io/docker/dockerfile-upstream:experimental:
------
rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`
```
</del>

**Comment by frol** [comment]
Have you tried changing the ports in `~/.near/config.json`?

```js
  "rpc": {
    "addr": "0.0.0.0:3031",
  ...
  "network": {
    "addr": "0.0.0.0:24568",
  ...
 ```

This works just fine for me.

**Comment by eorituz** [comment]
So as the title said I only tried running a second node on one machine as of now.
So it's not done with purely changing the `config.json`.
Nodelib [shuts down ](https://github.com/nearprotocol/nearcore/blob/master/scripts/nodelib.py#L136) all containers with the name `nearcore` and `watchtower`, so I had to rename the containers.
I retried it just now and it looks like I did some sort of different mistake, as my second node now runs.
Because my nodes are currently panicking I'll update everything and edit my initial comment.

However, running a second node on one machine isn't as easy as changing the ports in `~/.near/config.json`. You will need to read and somewhat understand the script's code and after all hardcode new container names in `nearcore/scripts/nodelib.py`. 
Here is a [gist](https://gist.github.com/eorituz/3b4b674cc596036f3cc54ef078366ddb) to my changed function in `nearcore/scripts/nodelib.py`.

**Comment by eorituz** [comment]
It also looks like there is a communication issue if you run two nodes on one machine.
The node that gets booted first finds peers and is able to sync. The second node, however, doesn't find any peers.

**Comment by frol** [comment]
Yeah, Docker deployment script is not designed to run several nodes at once.

**Comment by potatodepaulo** [comment]
Points assigned.
@ailisp is this in progress/is there an issue for this?

**Comment by ailisp** [comment]
It seems hard to fit this into current nearup model and would break a few things (track and shutdown proper near). Will create an issue on nearup

**Comment by potatodepaulo** [comment]
Issue addressed elsewhere, closing Stake Wars specific issue.
